
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Balance_General
	{
		private global::Gtk.VBox vbox11;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Label label12;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Alignment alignment21;

		private global::Gtk.Label label13;

		private global::Gtk.Entry txtFechaInicio;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Alignment alignment22;

		private global::Gtk.Label label14;

		private global::Gtk.Entry txtFechaFin;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.Button btnCalcular;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Balance_General
			this.Name = "Contabilidad_General.Balance_General";
			this.Title = global::Mono.Unix.Catalog.GetString("Balance_General");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Balance_General.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox10.Add(this.alignment9);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.alignment9]));
			w1.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox10.Add(this.alignment8);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.alignment8]));
			w2.Position = 1;
			// Container child hbox10.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox10.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox11.Add(this.hbox10);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox10]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			this.vbox12.BorderWidth = ((uint)(12));
			// Container child vbox12.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Balance General\n");
			this.vbox12.Add(this.label12);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label12]));
			w5.Position = 0;
			w5.Expand = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment21 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment21.Name = "alignment21";
			this.hbox7.Add(this.alignment21);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.alignment21]));
			w6.Position = 0;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de inicio:");
			this.hbox7.Add(this.label13);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label13]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.txtFechaInicio = new global::Gtk.Entry();
			this.txtFechaInicio.CanFocus = true;
			this.txtFechaInicio.Name = "txtFechaInicio";
			this.txtFechaInicio.IsEditable = true;
			this.txtFechaInicio.InvisibleChar = '•';
			this.hbox7.Add(this.txtFechaInicio);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.txtFechaInicio]));
			w8.Position = 2;
			this.vbox12.Add(this.hbox7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox7]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment22 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment22.Name = "alignment22";
			this.hbox8.Add(this.alignment22);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment22]));
			w10.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("     Fecha de fin:");
			this.hbox8.Add(this.label14);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label14]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.txtFechaFin = new global::Gtk.Entry();
			this.txtFechaFin.CanFocus = true;
			this.txtFechaFin.Name = "txtFechaFin";
			this.txtFechaFin.IsEditable = true;
			this.txtFechaFin.InvisibleChar = '•';
			this.hbox8.Add(this.txtFechaFin);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.txtFechaFin]));
			w12.Position = 2;
			this.vbox12.Add(this.hbox8);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox8]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox11.Add(this.vbox12);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.vbox12]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.hbox9.Add(this.alignment12);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.alignment12]));
			w15.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.hbox9.Add(this.alignment11);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.alignment11]));
			w16.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.btnCalcular = new global::Gtk.Button();
			this.btnCalcular.CanFocus = true;
			this.btnCalcular.Name = "btnCalcular";
			this.btnCalcular.UseUnderline = true;
			this.btnCalcular.Label = global::Mono.Unix.Catalog.GetString("Calcular");
			this.hbox9.Add(this.btnCalcular);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.btnCalcular]));
			w17.Position = 2;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(85));
			this.vbox11.Add(this.hbox9);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox9]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.Add(this.vbox11);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 229;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
