
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Control_de_Monedas
	{
		private global::Gtk.VBox vbox38;

		private global::Gtk.HBox hbox39;

		private global::Gtk.Alignment alignment36;

		private global::Gtk.Alignment alignment35;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox39;

		private global::Gtk.Label label52;

		private global::Gtk.HBox hbox42;

		private global::Gtk.HBox hbox46;

		private global::Gtk.Label label54;

		private global::Gtk.Entry txtBuscarISO;

		private global::Gtk.Button btnBuscarISO;

		private global::Gtk.HBox hbox45;

		private global::Gtk.Label label53;

		private global::Gtk.Entry txtBuscarNombre;

		private global::Gtk.Button btnBuscarNombre;

		private global::Gtk.HBox hbox41;

		private global::Gtk.ScrolledWindow scrolledwindow4;

		private global::Gtk.TreeView tvMonedas;

		private global::Gtk.VBox vbox40;

		private global::Gtk.Label label55;

		private global::Gtk.Label label56;

		private global::Gtk.VBox vbox43;

		private global::Gtk.Label label57;

		private global::Gtk.VBox vbox45;

		private global::Gtk.Label label58;

		private global::Gtk.Label label59;

		private global::Gtk.Label label60;

		private global::Gtk.VBox vbox41;

		private global::Gtk.Entry txtIDMoneda;

		private global::Gtk.Entry txtNombreMoneda;

		private global::Gtk.Entry txtCodigoISOMoneda;

		private global::Gtk.VBox vbox42;

		private global::Gtk.Entry txtPaisMoneda;

		private global::Gtk.VBox vbox44;

		private global::Gtk.Entry txtTasaConversion;

		private global::Gtk.ComboBox cmbActiva;

		private global::Gtk.HBox hbox40;

		private global::Gtk.Alignment alignment38;

		private global::Gtk.Alignment alignment37;

		private global::Gtk.HBox hbox47;

		private global::Gtk.Button btnNueva;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnaEditar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Control_de_Monedas
			this.Name = "Contabilidad_General.Control_de_Monedas";
			this.Title = global::Mono.Unix.Catalog.GetString("Control_de_Monedas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Control_de_Monedas.Gtk.Container+ContainerChild
			this.vbox38 = new global::Gtk.VBox();
			this.vbox38.Name = "vbox38";
			this.vbox38.Spacing = 6;
			// Container child vbox38.Gtk.Box+BoxChild
			this.hbox39 = new global::Gtk.HBox();
			this.hbox39.Name = "hbox39";
			this.hbox39.Spacing = 6;
			// Container child hbox39.Gtk.Box+BoxChild
			this.alignment36 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment36.Name = "alignment36";
			this.hbox39.Add(this.alignment36);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox39[this.alignment36]));
			w1.Position = 0;
			// Container child hbox39.Gtk.Box+BoxChild
			this.alignment35 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment35.Name = "alignment35";
			this.hbox39.Add(this.alignment35);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox39[this.alignment35]));
			w2.Position = 1;
			// Container child hbox39.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox39.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox39[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox38.Add(this.hbox39);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox38[this.hbox39]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox38.Gtk.Box+BoxChild
			this.vbox39 = new global::Gtk.VBox();
			this.vbox39.Name = "vbox39";
			this.vbox39.Spacing = 6;
			this.vbox39.BorderWidth = ((uint)(9));
			// Container child vbox39.Gtk.Box+BoxChild
			this.label52 = new global::Gtk.Label();
			this.label52.Name = "label52";
			this.label52.LabelProp = global::Mono.Unix.Catalog.GetString("Control de Monedas\n");
			this.vbox39.Add(this.label52);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox39[this.label52]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox39.Gtk.Box+BoxChild
			this.hbox42 = new global::Gtk.HBox();
			this.hbox42.Name = "hbox42";
			this.hbox42.Spacing = 6;
			// Container child hbox42.Gtk.Box+BoxChild
			this.hbox46 = new global::Gtk.HBox();
			this.hbox46.Name = "hbox46";
			this.hbox46.Spacing = 6;
			// Container child hbox46.Gtk.Box+BoxChild
			this.label54 = new global::Gtk.Label();
			this.label54.Name = "label54";
			this.label54.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por codigo ISO:");
			this.hbox46.Add(this.label54);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox46[this.label54]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox46.Gtk.Box+BoxChild
			this.txtBuscarISO = new global::Gtk.Entry();
			this.txtBuscarISO.CanFocus = true;
			this.txtBuscarISO.Name = "txtBuscarISO";
			this.txtBuscarISO.IsEditable = true;
			this.txtBuscarISO.InvisibleChar = '•';
			this.hbox46.Add(this.txtBuscarISO);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox46[this.txtBuscarISO]));
			w7.Position = 1;
			// Container child hbox46.Gtk.Box+BoxChild
			this.btnBuscarISO = new global::Gtk.Button();
			this.btnBuscarISO.CanFocus = true;
			this.btnBuscarISO.Name = "btnBuscarISO";
			this.btnBuscarISO.UseUnderline = true;
			this.btnBuscarISO.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox46.Add(this.btnBuscarISO);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox46[this.btnBuscarISO]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox42.Add(this.hbox46);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox42[this.hbox46]));
			w9.Position = 0;
			// Container child hbox42.Gtk.Box+BoxChild
			this.hbox45 = new global::Gtk.HBox();
			this.hbox45.Name = "hbox45";
			this.hbox45.Spacing = 6;
			// Container child hbox45.Gtk.Box+BoxChild
			this.label53 = new global::Gtk.Label();
			this.label53.Name = "label53";
			this.label53.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por nombre:");
			this.hbox45.Add(this.label53);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.label53]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox45.Gtk.Box+BoxChild
			this.txtBuscarNombre = new global::Gtk.Entry();
			this.txtBuscarNombre.CanFocus = true;
			this.txtBuscarNombre.Name = "txtBuscarNombre";
			this.txtBuscarNombre.IsEditable = true;
			this.txtBuscarNombre.InvisibleChar = '•';
			this.hbox45.Add(this.txtBuscarNombre);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.txtBuscarNombre]));
			w11.Position = 1;
			// Container child hbox45.Gtk.Box+BoxChild
			this.btnBuscarNombre = new global::Gtk.Button();
			this.btnBuscarNombre.CanFocus = true;
			this.btnBuscarNombre.Name = "btnBuscarNombre";
			this.btnBuscarNombre.UseUnderline = true;
			this.btnBuscarNombre.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox45.Add(this.btnBuscarNombre);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox45[this.btnBuscarNombre]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox42.Add(this.hbox45);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox42[this.hbox45]));
			w13.Position = 1;
			this.vbox39.Add(this.hbox42);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox39[this.hbox42]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox39.Gtk.Box+BoxChild
			this.hbox41 = new global::Gtk.HBox();
			this.hbox41.Name = "hbox41";
			this.hbox41.Spacing = 6;
			// Container child hbox41.Gtk.Box+BoxChild
			this.scrolledwindow4 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow4.CanFocus = true;
			this.scrolledwindow4.Name = "scrolledwindow4";
			this.scrolledwindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow4.Gtk.Container+ContainerChild
			this.tvMonedas = new global::Gtk.TreeView();
			this.tvMonedas.CanFocus = true;
			this.tvMonedas.Name = "tvMonedas";
			this.scrolledwindow4.Add(this.tvMonedas);
			this.hbox41.Add(this.scrolledwindow4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.scrolledwindow4]));
			w16.Position = 0;
			// Container child hbox41.Gtk.Box+BoxChild
			this.vbox40 = new global::Gtk.VBox();
			this.vbox40.Name = "vbox40";
			this.vbox40.Spacing = 6;
			// Container child vbox40.Gtk.Box+BoxChild
			this.label55 = new global::Gtk.Label();
			this.label55.Name = "label55";
			this.label55.Xalign = 1F;
			this.label55.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la Moneda:");
			this.vbox40.Add(this.label55);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox40[this.label55]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(14));
			// Container child vbox40.Gtk.Box+BoxChild
			this.label56 = new global::Gtk.Label();
			this.label56.Name = "label56";
			this.label56.Xalign = 1F;
			this.label56.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de la Moneda:");
			this.vbox40.Add(this.label56);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox40[this.label56]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox40.Gtk.Box+BoxChild
			this.vbox43 = new global::Gtk.VBox();
			this.vbox43.Name = "vbox43";
			this.vbox43.Spacing = 6;
			// Container child vbox43.Gtk.Box+BoxChild
			this.label57 = new global::Gtk.Label();
			this.label57.Name = "label57";
			this.label57.Xalign = 1F;
			this.label57.LabelProp = global::Mono.Unix.Catalog.GetString("Codigo ISO de la Moneda:");
			this.vbox43.Add(this.label57);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox43[this.label57]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(14));
			// Container child vbox43.Gtk.Box+BoxChild
			this.vbox45 = new global::Gtk.VBox();
			this.vbox45.Name = "vbox45";
			this.vbox45.Spacing = 6;
			// Container child vbox45.Gtk.Box+BoxChild
			this.label58 = new global::Gtk.Label();
			this.label58.Name = "label58";
			this.label58.Xalign = 1F;
			this.label58.LabelProp = global::Mono.Unix.Catalog.GetString("Pais de la Moneda:");
			this.vbox45.Add(this.label58);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox45[this.label58]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox45.Gtk.Box+BoxChild
			this.label59 = new global::Gtk.Label();
			this.label59.Name = "label59";
			this.label59.Xalign = 1F;
			this.label59.LabelProp = global::Mono.Unix.Catalog.GetString("Tasa de Conversion:");
			this.vbox45.Add(this.label59);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox45[this.label59]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(18));
			// Container child vbox45.Gtk.Box+BoxChild
			this.label60 = new global::Gtk.Label();
			this.label60.Name = "label60";
			this.label60.Xalign = 1F;
			this.label60.LabelProp = global::Mono.Unix.Catalog.GetString("Activa:");
			this.vbox45.Add(this.label60);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox45[this.label60]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox43.Add(this.vbox45);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox43[this.vbox45]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox40.Add(this.vbox43);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox40[this.vbox43]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox41.Add(this.vbox40);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.vbox40]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox41.Gtk.Box+BoxChild
			this.vbox41 = new global::Gtk.VBox();
			this.vbox41.Name = "vbox41";
			this.vbox41.Spacing = 6;
			// Container child vbox41.Gtk.Box+BoxChild
			this.txtIDMoneda = new global::Gtk.Entry();
			this.txtIDMoneda.CanFocus = true;
			this.txtIDMoneda.Name = "txtIDMoneda";
			this.txtIDMoneda.IsEditable = true;
			this.txtIDMoneda.InvisibleChar = '•';
			this.vbox41.Add(this.txtIDMoneda);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox41[this.txtIDMoneda]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			w26.Padding = ((uint)(6));
			// Container child vbox41.Gtk.Box+BoxChild
			this.txtNombreMoneda = new global::Gtk.Entry();
			this.txtNombreMoneda.CanFocus = true;
			this.txtNombreMoneda.Name = "txtNombreMoneda";
			this.txtNombreMoneda.IsEditable = true;
			this.txtNombreMoneda.InvisibleChar = '•';
			this.vbox41.Add(this.txtNombreMoneda);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox41[this.txtNombreMoneda]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox41.Gtk.Box+BoxChild
			this.txtCodigoISOMoneda = new global::Gtk.Entry();
			this.txtCodigoISOMoneda.CanFocus = true;
			this.txtCodigoISOMoneda.Name = "txtCodigoISOMoneda";
			this.txtCodigoISOMoneda.IsEditable = true;
			this.txtCodigoISOMoneda.InvisibleChar = '•';
			this.vbox41.Add(this.txtCodigoISOMoneda);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox41[this.txtCodigoISOMoneda]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			w28.Padding = ((uint)(3));
			// Container child vbox41.Gtk.Box+BoxChild
			this.vbox42 = new global::Gtk.VBox();
			this.vbox42.Name = "vbox42";
			this.vbox42.Spacing = 6;
			// Container child vbox42.Gtk.Box+BoxChild
			this.txtPaisMoneda = new global::Gtk.Entry();
			this.txtPaisMoneda.CanFocus = true;
			this.txtPaisMoneda.Name = "txtPaisMoneda";
			this.txtPaisMoneda.IsEditable = true;
			this.txtPaisMoneda.InvisibleChar = '•';
			this.vbox42.Add(this.txtPaisMoneda);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox42[this.txtPaisMoneda]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			w29.Padding = ((uint)(3));
			// Container child vbox42.Gtk.Box+BoxChild
			this.vbox44 = new global::Gtk.VBox();
			this.vbox44.Name = "vbox44";
			this.vbox44.Spacing = 6;
			// Container child vbox44.Gtk.Box+BoxChild
			this.txtTasaConversion = new global::Gtk.Entry();
			this.txtTasaConversion.CanFocus = true;
			this.txtTasaConversion.Name = "txtTasaConversion";
			this.txtTasaConversion.IsEditable = true;
			this.txtTasaConversion.InvisibleChar = '•';
			this.vbox44.Add(this.txtTasaConversion);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox44[this.txtTasaConversion]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(3));
			// Container child vbox44.Gtk.Box+BoxChild
			this.cmbActiva = global::Gtk.ComboBox.NewText();
			this.cmbActiva.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbActiva.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbActiva.Name = "cmbActiva";
			this.cmbActiva.Active = 0;
			this.vbox44.Add(this.cmbActiva);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox44[this.cmbActiva]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.vbox42.Add(this.vbox44);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox42[this.vbox44]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			this.vbox41.Add(this.vbox42);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox41[this.vbox42]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox41.Add(this.vbox41);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox41[this.vbox41]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox39.Add(this.hbox41);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox39[this.hbox41]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox38.Add(this.vbox39);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox38[this.vbox39]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox38.Gtk.Box+BoxChild
			this.hbox40 = new global::Gtk.HBox();
			this.hbox40.Name = "hbox40";
			this.hbox40.Spacing = 6;
			// Container child hbox40.Gtk.Box+BoxChild
			this.alignment38 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment38.Name = "alignment38";
			this.hbox40.Add(this.alignment38);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox40[this.alignment38]));
			w37.Position = 0;
			// Container child hbox40.Gtk.Box+BoxChild
			this.alignment37 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment37.Name = "alignment37";
			this.hbox40.Add(this.alignment37);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox40[this.alignment37]));
			w38.Position = 1;
			// Container child hbox40.Gtk.Box+BoxChild
			this.hbox47 = new global::Gtk.HBox();
			this.hbox47.Name = "hbox47";
			this.hbox47.Spacing = 6;
			// Container child hbox47.Gtk.Box+BoxChild
			this.btnNueva = new global::Gtk.Button();
			this.btnNueva.CanFocus = true;
			this.btnNueva.Name = "btnNueva";
			this.btnNueva.UseUnderline = true;
			this.btnNueva.BorderWidth = ((uint)(3));
			this.btnNueva.Label = global::Mono.Unix.Catalog.GetString("Nueva");
			this.hbox47.Add(this.btnNueva);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.btnNueva]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox47.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.BorderWidth = ((uint)(3));
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox47.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.btnAgregar]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox47.Gtk.Box+BoxChild
			this.btnaEditar = new global::Gtk.Button();
			this.btnaEditar.CanFocus = true;
			this.btnaEditar.Name = "btnaEditar";
			this.btnaEditar.UseUnderline = true;
			this.btnaEditar.BorderWidth = ((uint)(3));
			this.btnaEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox47.Add(this.btnaEditar);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox47[this.btnaEditar]));
			w41.Position = 2;
			this.hbox40.Add(this.hbox47);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox40[this.hbox47]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox38.Add(this.hbox40);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox38[this.hbox40]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.Add(this.vbox38);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 797;
			this.DefaultHeight = 428;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
