
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Control_de_Asientos_Contables
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label3;

		private global::Gtk.Entry txtBuscarCodigo;

		private global::Gtk.Button btnBuscarCodigo;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label2;

		private global::Gtk.Entry txtBuscarFecha;

		private global::Gtk.Button btnBuscarFecha;

		private global::Gtk.HBox hbox5;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.TreeView tvAsientosContables;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Label label7;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label8;

		private global::Gtk.Label label9;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Label label10;

		private global::Gtk.Label label6;

		private global::Gtk.Label label11;

		private global::Gtk.Label label12;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Entry txtIDAsiento;

		private global::Gtk.Entry txtCodigoAsiento;

		private global::Gtk.VBox vbox4;

		private global::Gtk.ComboBox cmbIDCuentaDebe;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Entry txtImporteDebe;

		private global::Gtk.ComboBox cmbIDCuentaHaber;

		private global::Gtk.Entry txtImporteHaber;

		private global::Gtk.VBox vbox6;

		private global::Gtk.ComboBox cmbActivo;

		private global::Gtk.Entry txtFechaAsiento;

		private global::Gtk.ComboBox cmbIDCatalogoCuentas;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Alignment alignment4;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.Alignment alignment3;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button btnNuevo;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnEditar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Control_de_Asientos_Contables
			this.Name = "Contabilidad_General.Control_de_Asientos_Contables";
			this.Title = global::Mono.Unix.Catalog.GetString("Control_de_Asientos_Contables");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Control_de_Asientos_Contables.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.alignment6 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.alignment2.Add(this.alignment6);
			this.hbox1.Add(this.alignment2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment2]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment1.Add(this.alignment5);
			this.hbox1.Add(this.alignment1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment1]));
			w4.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox1.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.btnSalir]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(12));
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Control de Asientos Contables\n");
			this.vbox2.Add(this.label1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por Codigo:");
			this.hbox7.Add(this.label3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label3]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.txtBuscarCodigo = new global::Gtk.Entry();
			this.txtBuscarCodigo.CanFocus = true;
			this.txtBuscarCodigo.Name = "txtBuscarCodigo";
			this.txtBuscarCodigo.IsEditable = true;
			this.txtBuscarCodigo.InvisibleChar = '•';
			this.hbox7.Add(this.txtBuscarCodigo);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.txtBuscarCodigo]));
			w9.Position = 1;
			// Container child hbox7.Gtk.Box+BoxChild
			this.btnBuscarCodigo = new global::Gtk.Button();
			this.btnBuscarCodigo.CanFocus = true;
			this.btnBuscarCodigo.Name = "btnBuscarCodigo";
			this.btnBuscarCodigo.UseUnderline = true;
			this.btnBuscarCodigo.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox7.Add(this.btnBuscarCodigo);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.btnBuscarCodigo]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox4.Add(this.hbox7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox7]));
			w11.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por Fecha:");
			this.hbox6.Add(this.label2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label2]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.txtBuscarFecha = new global::Gtk.Entry();
			this.txtBuscarFecha.CanFocus = true;
			this.txtBuscarFecha.Name = "txtBuscarFecha";
			this.txtBuscarFecha.IsEditable = true;
			this.txtBuscarFecha.InvisibleChar = '•';
			this.hbox6.Add(this.txtBuscarFecha);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.txtBuscarFecha]));
			w13.Position = 1;
			// Container child hbox6.Gtk.Box+BoxChild
			this.btnBuscarFecha = new global::Gtk.Button();
			this.btnBuscarFecha.CanFocus = true;
			this.btnBuscarFecha.Name = "btnBuscarFecha";
			this.btnBuscarFecha.UseUnderline = true;
			this.btnBuscarFecha.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox6.Add(this.btnBuscarFecha);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.btnBuscarFecha]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.hbox4.Add(this.hbox6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.hbox6]));
			w15.Position = 1;
			this.vbox2.Add(this.hbox4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w16.Position = 1;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.scrolledwindow1.BorderWidth = ((uint)(6));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.tvAsientosContables = new global::Gtk.TreeView();
			this.tvAsientosContables.CanFocus = true;
			this.tvAsientosContables.Name = "tvAsientosContables";
			this.scrolledwindow1.Add(this.tvAsientosContables);
			this.hbox5.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.scrolledwindow1]));
			w18.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			this.vbox7.BorderWidth = ((uint)(3));
			// Container child vbox7.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Asiento:");
			this.vbox7.Add(this.label4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label4]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(13));
			// Container child vbox7.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Codigo del Asiento:");
			this.vbox7.Add(this.label5);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label5]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			w20.Padding = ((uint)(4));
			// Container child vbox7.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la Cuenta debe:");
			this.vbox8.Add(this.label7);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label7]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(8));
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Importe debe:");
			this.vbox9.Add(this.label8);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label8]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			w22.Padding = ((uint)(10));
			// Container child vbox9.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la Cuenta Haber:");
			this.vbox9.Add(this.label9);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label9]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(7));
			// Container child vbox9.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Importe haber:");
			this.vbox10.Add(this.label10);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label10]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(11));
			// Container child vbox10.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.Xalign = 1F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Activo:");
			this.vbox10.Add(this.label6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label6]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			w25.Padding = ((uint)(12));
			// Container child vbox10.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.Xalign = 1F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha del Asiento:");
			this.vbox10.Add(this.label11);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label11]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			w26.Padding = ((uint)(12));
			// Container child vbox10.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.Xalign = 1F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("ID del catalogo de cuentas:");
			this.vbox10.Add(this.label12);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.label12]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox9.Add(this.vbox10);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.vbox10]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox8.Add(this.vbox9);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			this.vbox7.Add(this.vbox8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.vbox8]));
			w30.Position = 2;
			w30.Expand = false;
			w30.Fill = false;
			this.hbox5.Add(this.vbox7);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox7]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtIDAsiento = new global::Gtk.Entry();
			this.txtIDAsiento.CanFocus = true;
			this.txtIDAsiento.Name = "txtIDAsiento";
			this.txtIDAsiento.IsEditable = true;
			this.txtIDAsiento.InvisibleChar = '•';
			this.vbox3.Add(this.txtIDAsiento);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.txtIDAsiento]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			w32.Padding = ((uint)(7));
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtCodigoAsiento = new global::Gtk.Entry();
			this.txtCodigoAsiento.CanFocus = true;
			this.txtCodigoAsiento.Name = "txtCodigoAsiento";
			this.txtCodigoAsiento.IsEditable = true;
			this.txtCodigoAsiento.InvisibleChar = '•';
			this.vbox3.Add(this.txtCodigoAsiento);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.txtCodigoAsiento]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			w33.Padding = ((uint)(3));
			// Container child vbox3.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.cmbIDCuentaDebe = global::Gtk.ComboBox.NewText();
			this.cmbIDCuentaDebe.Name = "cmbIDCuentaDebe";
			this.vbox4.Add(this.cmbIDCuentaDebe);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.cmbIDCuentaDebe]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			w34.Padding = ((uint)(3));
			// Container child vbox4.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.txtImporteDebe = new global::Gtk.Entry();
			this.txtImporteDebe.CanFocus = true;
			this.txtImporteDebe.Name = "txtImporteDebe";
			this.txtImporteDebe.IsEditable = true;
			this.txtImporteDebe.InvisibleChar = '•';
			this.vbox5.Add(this.txtImporteDebe);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.txtImporteDebe]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			w35.Padding = ((uint)(3));
			// Container child vbox5.Gtk.Box+BoxChild
			this.cmbIDCuentaHaber = global::Gtk.ComboBox.NewText();
			this.cmbIDCuentaHaber.Name = "cmbIDCuentaHaber";
			this.vbox5.Add(this.cmbIDCuentaHaber);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.cmbIDCuentaHaber]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			w36.Padding = ((uint)(3));
			// Container child vbox5.Gtk.Box+BoxChild
			this.txtImporteHaber = new global::Gtk.Entry();
			this.txtImporteHaber.CanFocus = true;
			this.txtImporteHaber.Name = "txtImporteHaber";
			this.txtImporteHaber.IsEditable = true;
			this.txtImporteHaber.InvisibleChar = '•';
			this.vbox5.Add(this.txtImporteHaber);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.txtImporteHaber]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			w37.Padding = ((uint)(3));
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.cmbActivo = global::Gtk.ComboBox.NewText();
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbActivo.Name = "cmbActivo";
			this.cmbActivo.Active = 0;
			this.vbox6.Add(this.cmbActivo);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.cmbActivo]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			w38.Padding = ((uint)(3));
			// Container child vbox6.Gtk.Box+BoxChild
			this.txtFechaAsiento = new global::Gtk.Entry();
			this.txtFechaAsiento.CanFocus = true;
			this.txtFechaAsiento.Name = "txtFechaAsiento";
			this.txtFechaAsiento.IsEditable = true;
			this.txtFechaAsiento.InvisibleChar = '•';
			this.vbox6.Add(this.txtFechaAsiento);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.txtFechaAsiento]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			w39.Padding = ((uint)(3));
			// Container child vbox6.Gtk.Box+BoxChild
			this.cmbIDCatalogoCuentas = global::Gtk.ComboBox.NewText();
			this.cmbIDCatalogoCuentas.Name = "cmbIDCatalogoCuentas";
			this.vbox6.Add(this.cmbIDCatalogoCuentas);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.cmbIDCatalogoCuentas]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox5.Add(this.vbox6);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.vbox6]));
			w41.Position = 3;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox4.Add(this.vbox5);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.vbox5]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox3.Add(this.vbox4);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.vbox4]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.hbox5.Add(this.vbox3);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox3]));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w45.Position = 2;
			w45.Expand = false;
			w45.Fill = false;
			this.vbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox2]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			// Container child alignment4.Gtk.Container+ContainerChild
			this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.alignment4.Add(this.alignment8);
			this.hbox2.Add(this.alignment4);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment4]));
			w48.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			// Container child alignment3.Gtk.Container+ContainerChild
			this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.alignment3.Add(this.alignment7);
			this.hbox2.Add(this.alignment3);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.alignment3]));
			w50.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnNuevo = new global::Gtk.Button();
			this.btnNuevo.CanFocus = true;
			this.btnNuevo.Name = "btnNuevo";
			this.btnNuevo.UseUnderline = true;
			this.btnNuevo.BorderWidth = ((uint)(3));
			this.btnNuevo.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.hbox3.Add(this.btnNuevo);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnNuevo]));
			w51.Position = 0;
			w51.Expand = false;
			w51.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.BorderWidth = ((uint)(3));
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox3.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnAgregar]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.BorderWidth = ((uint)(3));
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox3.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.btnEditar]));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			this.hbox2.Add(this.hbox3);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbox3]));
			w54.Position = 2;
			w54.Expand = false;
			w54.Fill = false;
			this.vbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w55.Position = 2;
			w55.Expand = false;
			w55.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 884;
			this.DefaultHeight = 576;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
