
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Control_de_Libro_Mayor
	{
		private global::Gtk.VBox vbox23;

		private global::Gtk.HBox hbox16;

		private global::Gtk.Alignment alignment14;

		private global::Gtk.Alignment alignment13;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox24;

		private global::Gtk.Label label28;

		private global::Gtk.HBox hbox20;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Label label31;

		private global::Gtk.Entry txtBuscarID;

		private global::Gtk.Button btnBuscarID;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Label label30;

		private global::Gtk.Entry txtBuscarMes;

		private global::Gtk.Button btnBuscarMes;

		private global::Gtk.HBox hbox19;

		private global::Gtk.ScrolledWindow scrolledwindow3;

		private global::Gtk.TreeView treeview3;

		private global::Gtk.VBox vbox26;

		private global::Gtk.Label label32;

		private global::Gtk.Label label43;

		private global::Gtk.Label label8;

		private global::Gtk.Label label33;

		private global::Gtk.VBox vbox28;

		private global::Gtk.Label label34;

		private global::Gtk.Label label7;

		private global::Gtk.Label label35;

		private global::Gtk.VBox vbox30;

		private global::Gtk.Label label38;

		private global::Gtk.Label label6;

		private global::Gtk.VBox vbox25;

		private global::Gtk.Entry txtIDLibroMayor;

		private global::Gtk.ComboBox cmbMesLibroMayor;

		private global::Gtk.Entry txtConceptoMovimiento;

		private global::Gtk.VBox vbox27;

		private global::Gtk.Entry txtTotalHaber;

		private global::Gtk.Entry txtTotalDebe;

		private global::Gtk.ComboBox cmbActivo;

		private global::Gtk.VBox vbox29;

		private global::Gtk.ComboBox cmbIDAsientoContable;

		private global::Gtk.ComboBox cmbIDPeridoContable;

		private global::Gtk.VBox vbox31;

		private global::Gtk.ComboBox cmbIDCatalogoCuentas;

		private global::Gtk.HBox hbox17;

		private global::Gtk.Alignment alignment16;

		private global::Gtk.Alignment alignment15;

		private global::Gtk.HBox hbox18;

		private global::Gtk.Button btnNuevo;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnEditar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Control_de_Libro_Mayor
			this.Name = "Contabilidad_General.Control_de_Libro_Mayor";
			this.Title = global::Mono.Unix.Catalog.GetString("Control_de_Libro_Mayor");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Control_de_Libro_Mayor.Gtk.Container+ContainerChild
			this.vbox23 = new global::Gtk.VBox();
			this.vbox23.Name = "vbox23";
			this.vbox23.Spacing = 6;
			// Container child vbox23.Gtk.Box+BoxChild
			this.hbox16 = new global::Gtk.HBox();
			this.hbox16.Name = "hbox16";
			this.hbox16.Spacing = 6;
			// Container child hbox16.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			this.hbox16.Add(this.alignment14);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.alignment14]));
			w1.Position = 0;
			// Container child hbox16.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			this.hbox16.Add(this.alignment13);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.alignment13]));
			w2.Position = 1;
			// Container child hbox16.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox16.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox16[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox23.Add(this.hbox16);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.hbox16]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.vbox24 = new global::Gtk.VBox();
			this.vbox24.Name = "vbox24";
			this.vbox24.Spacing = 6;
			this.vbox24.BorderWidth = ((uint)(9));
			// Container child vbox24.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Control del Libro Mayor\n");
			this.vbox24.Add(this.label28);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.label28]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label31 = new global::Gtk.Label();
			this.label31.Name = "label31";
			this.label31.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID:");
			this.hbox22.Add(this.label31);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label31]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox22.Gtk.Box+BoxChild
			this.txtBuscarID = new global::Gtk.Entry();
			this.txtBuscarID.CanFocus = true;
			this.txtBuscarID.Name = "txtBuscarID";
			this.txtBuscarID.IsEditable = true;
			this.txtBuscarID.InvisibleChar = '•';
			this.hbox22.Add(this.txtBuscarID);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.txtBuscarID]));
			w7.Position = 1;
			// Container child hbox22.Gtk.Box+BoxChild
			this.btnBuscarID = new global::Gtk.Button();
			this.btnBuscarID.CanFocus = true;
			this.btnBuscarID.Name = "btnBuscarID";
			this.btnBuscarID.UseUnderline = true;
			this.btnBuscarID.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox22.Add(this.btnBuscarID);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.btnBuscarID]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox20.Add(this.hbox22);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.hbox22]));
			w9.Position = 0;
			// Container child hbox20.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label30 = new global::Gtk.Label();
			this.label30.Name = "label30";
			this.label30.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por Mes:");
			this.hbox21.Add(this.label30);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label30]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.txtBuscarMes = new global::Gtk.Entry();
			this.txtBuscarMes.CanFocus = true;
			this.txtBuscarMes.Name = "txtBuscarMes";
			this.txtBuscarMes.IsEditable = true;
			this.txtBuscarMes.InvisibleChar = '•';
			this.hbox21.Add(this.txtBuscarMes);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.txtBuscarMes]));
			w11.Position = 1;
			// Container child hbox21.Gtk.Box+BoxChild
			this.btnBuscarMes = new global::Gtk.Button();
			this.btnBuscarMes.CanFocus = true;
			this.btnBuscarMes.Name = "btnBuscarMes";
			this.btnBuscarMes.UseUnderline = true;
			this.btnBuscarMes.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox21.Add(this.btnBuscarMes);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.btnBuscarMes]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox20.Add(this.hbox21);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.hbox21]));
			w13.Position = 1;
			this.vbox24.Add(this.hbox20);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox20]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox24.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.scrolledwindow3 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow3.CanFocus = true;
			this.scrolledwindow3.Name = "scrolledwindow3";
			this.scrolledwindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow3.Gtk.Container+ContainerChild
			this.treeview3 = new global::Gtk.TreeView();
			this.treeview3.CanFocus = true;
			this.treeview3.Name = "treeview3";
			this.scrolledwindow3.Add(this.treeview3);
			this.hbox19.Add(this.scrolledwindow3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.scrolledwindow3]));
			w16.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox26 = new global::Gtk.VBox();
			this.vbox26.Name = "vbox26";
			this.vbox26.Spacing = 6;
			// Container child vbox26.Gtk.Box+BoxChild
			this.label32 = new global::Gtk.Label();
			this.label32.Name = "label32";
			this.label32.Xalign = 1F;
			this.label32.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Libro Mayor:");
			this.vbox26.Add(this.label32);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.label32]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(9));
			// Container child vbox26.Gtk.Box+BoxChild
			this.label43 = new global::Gtk.Label();
			this.label43.Name = "label43";
			this.label43.Xalign = 1F;
			this.label43.LabelProp = global::Mono.Unix.Catalog.GetString("Mes del Libro Mayor:");
			this.vbox26.Add(this.label43);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.label43]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(13));
			// Container child vbox26.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.Xalign = 1F;
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Concepto del Movimiento:");
			this.vbox26.Add(this.label8);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.label8]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(6));
			// Container child vbox26.Gtk.Box+BoxChild
			this.label33 = new global::Gtk.Label();
			this.label33.Name = "label33";
			this.label33.Xalign = 1F;
			this.label33.LabelProp = global::Mono.Unix.Catalog.GetString("Total Haber:");
			this.vbox26.Add(this.label33);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.label33]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			w20.Padding = ((uint)(12));
			// Container child vbox26.Gtk.Box+BoxChild
			this.vbox28 = new global::Gtk.VBox();
			this.vbox28.Name = "vbox28";
			this.vbox28.Spacing = 6;
			// Container child vbox28.Gtk.Box+BoxChild
			this.label34 = new global::Gtk.Label();
			this.label34.Name = "label34";
			this.label34.Xalign = 1F;
			this.label34.LabelProp = global::Mono.Unix.Catalog.GetString("Total Debe:");
			this.vbox28.Add(this.label34);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.label34]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(9));
			// Container child vbox28.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.Xalign = 1F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Activo:");
			this.vbox28.Add(this.label7);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.label7]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			w22.Padding = ((uint)(6));
			// Container child vbox28.Gtk.Box+BoxChild
			this.label35 = new global::Gtk.Label();
			this.label35.Name = "label35";
			this.label35.Xalign = 1F;
			this.label35.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Asiento Contable:");
			this.vbox28.Add(this.label35);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.label35]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(17));
			// Container child vbox28.Gtk.Box+BoxChild
			this.vbox30 = new global::Gtk.VBox();
			this.vbox30.Name = "vbox30";
			this.vbox30.Spacing = 6;
			// Container child vbox30.Gtk.Box+BoxChild
			this.label38 = new global::Gtk.Label();
			this.label38.Name = "label38";
			this.label38.Xalign = 1F;
			this.label38.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Periodo Contable:");
			this.vbox30.Add(this.label38);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.label38]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(12));
			// Container child vbox30.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Catalogo de Cuentas:");
			this.vbox30.Add(this.label6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox30[this.label6]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			w25.Padding = ((uint)(14));
			this.vbox28.Add(this.vbox30);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox28[this.vbox30]));
			w26.Position = 3;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox26.Add(this.vbox28);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox26[this.vbox28]));
			w27.Position = 4;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox19.Add(this.vbox26);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox26]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox19.Gtk.Box+BoxChild
			this.vbox25 = new global::Gtk.VBox();
			this.vbox25.Name = "vbox25";
			this.vbox25.Spacing = 6;
			// Container child vbox25.Gtk.Box+BoxChild
			this.txtIDLibroMayor = new global::Gtk.Entry();
			this.txtIDLibroMayor.CanFocus = true;
			this.txtIDLibroMayor.Name = "txtIDLibroMayor";
			this.txtIDLibroMayor.IsEditable = true;
			this.txtIDLibroMayor.InvisibleChar = '•';
			this.vbox25.Add(this.txtIDLibroMayor);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.txtIDLibroMayor]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			w29.Padding = ((uint)(4));
			// Container child vbox25.Gtk.Box+BoxChild
			this.cmbMesLibroMayor = global::Gtk.ComboBox.NewText();
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Enero"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Febrero"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Marzo"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Abril"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Mayo"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Junio"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Julio"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Agosto"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Septiembre"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Octubre"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Noviembre"));
			this.cmbMesLibroMayor.AppendText(global::Mono.Unix.Catalog.GetString("Diciembre"));
			this.cmbMesLibroMayor.Name = "cmbMesLibroMayor";
			this.vbox25.Add(this.cmbMesLibroMayor);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.cmbMesLibroMayor]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(5));
			// Container child vbox25.Gtk.Box+BoxChild
			this.txtConceptoMovimiento = new global::Gtk.Entry();
			this.txtConceptoMovimiento.CanFocus = true;
			this.txtConceptoMovimiento.Name = "txtConceptoMovimiento";
			this.txtConceptoMovimiento.IsEditable = true;
			this.txtConceptoMovimiento.InvisibleChar = '•';
			this.vbox25.Add(this.txtConceptoMovimiento);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.txtConceptoMovimiento]));
			w31.Position = 2;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox25.Gtk.Box+BoxChild
			this.vbox27 = new global::Gtk.VBox();
			this.vbox27.Name = "vbox27";
			this.vbox27.Spacing = 6;
			// Container child vbox27.Gtk.Box+BoxChild
			this.txtTotalHaber = new global::Gtk.Entry();
			this.txtTotalHaber.CanFocus = true;
			this.txtTotalHaber.Name = "txtTotalHaber";
			this.txtTotalHaber.IsEditable = true;
			this.txtTotalHaber.InvisibleChar = '•';
			this.vbox27.Add(this.txtTotalHaber);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.txtTotalHaber]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			w32.Padding = ((uint)(8));
			// Container child vbox27.Gtk.Box+BoxChild
			this.txtTotalDebe = new global::Gtk.Entry();
			this.txtTotalDebe.CanFocus = true;
			this.txtTotalDebe.Name = "txtTotalDebe";
			this.txtTotalDebe.IsEditable = true;
			this.txtTotalDebe.InvisibleChar = '•';
			this.vbox27.Add(this.txtTotalDebe);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.txtTotalDebe]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			w33.Padding = ((uint)(4));
			// Container child vbox27.Gtk.Box+BoxChild
			this.cmbActivo = global::Gtk.ComboBox.NewText();
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbActivo.Name = "cmbActivo";
			this.cmbActivo.Active = 0;
			this.vbox27.Add(this.cmbActivo);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.cmbActivo]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox27.Gtk.Box+BoxChild
			this.vbox29 = new global::Gtk.VBox();
			this.vbox29.Name = "vbox29";
			this.vbox29.Spacing = 6;
			// Container child vbox29.Gtk.Box+BoxChild
			this.cmbIDAsientoContable = global::Gtk.ComboBox.NewText();
			this.cmbIDAsientoContable.Name = "cmbIDAsientoContable";
			this.vbox29.Add(this.cmbIDAsientoContable);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.cmbIDAsientoContable]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			w35.Padding = ((uint)(6));
			// Container child vbox29.Gtk.Box+BoxChild
			this.cmbIDPeridoContable = global::Gtk.ComboBox.NewText();
			this.cmbIDPeridoContable.Name = "cmbIDPeridoContable";
			this.vbox29.Add(this.cmbIDPeridoContable);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.cmbIDPeridoContable]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			w36.Padding = ((uint)(12));
			// Container child vbox29.Gtk.Box+BoxChild
			this.vbox31 = new global::Gtk.VBox();
			this.vbox31.Name = "vbox31";
			this.vbox31.Spacing = 6;
			// Container child vbox31.Gtk.Box+BoxChild
			this.cmbIDCatalogoCuentas = global::Gtk.ComboBox.NewText();
			this.cmbIDCatalogoCuentas.Name = "cmbIDCatalogoCuentas";
			this.vbox31.Add(this.cmbIDCatalogoCuentas);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox31[this.cmbIDCatalogoCuentas]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			w37.Padding = ((uint)(4));
			this.vbox29.Add(this.vbox31);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox29[this.vbox31]));
			w38.Position = 2;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox27.Add(this.vbox29);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox27[this.vbox29]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox25.Add(this.vbox27);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox25[this.vbox27]));
			w40.Position = 3;
			w40.Expand = false;
			w40.Fill = false;
			this.hbox19.Add(this.vbox25);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.vbox25]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox24.Add(this.hbox19);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox24[this.hbox19]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox23.Add(this.vbox24);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.vbox24]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox23.Gtk.Box+BoxChild
			this.hbox17 = new global::Gtk.HBox();
			this.hbox17.Name = "hbox17";
			this.hbox17.Spacing = 6;
			// Container child hbox17.Gtk.Box+BoxChild
			this.alignment16 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment16.Name = "alignment16";
			this.hbox17.Add(this.alignment16);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.alignment16]));
			w44.Position = 0;
			// Container child hbox17.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			this.hbox17.Add(this.alignment15);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.alignment15]));
			w45.Position = 1;
			// Container child hbox17.Gtk.Box+BoxChild
			this.hbox18 = new global::Gtk.HBox();
			this.hbox18.Name = "hbox18";
			this.hbox18.Spacing = 6;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnNuevo = new global::Gtk.Button();
			this.btnNuevo.CanFocus = true;
			this.btnNuevo.Name = "btnNuevo";
			this.btnNuevo.UseUnderline = true;
			this.btnNuevo.BorderWidth = ((uint)(6));
			this.btnNuevo.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.hbox18.Add(this.btnNuevo);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnNuevo]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.BorderWidth = ((uint)(6));
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox18.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnAgregar]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox18.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.BorderWidth = ((uint)(6));
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox18.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox18[this.btnEditar]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox17.Add(this.hbox18);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox17[this.hbox18]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			this.vbox23.Add(this.hbox17);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox23[this.hbox17]));
			w50.Position = 2;
			w50.Expand = false;
			w50.Fill = false;
			this.Add(this.vbox23);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 746;
			this.DefaultHeight = 599;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
