
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Control_de_Empresa
	{
		private global::Gtk.VBox vbox15;

		private global::Gtk.HBox hbox19;

		private global::Gtk.Alignment alignment24;

		private global::Gtk.Alignment alignment23;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Label label19;

		private global::Gtk.HBox hbox20;

		private global::Gtk.HBox hbox22;

		private global::Gtk.Label label22;

		private global::Gtk.Entry txtBuscarID;

		private global::Gtk.Button btnBuscarID;

		private global::Gtk.HBox hbox21;

		private global::Gtk.Label label21;

		private global::Gtk.Entry txtBuscarNombre;

		private global::Gtk.Button btnBuscarNombre;

		private global::Gtk.HBox hbox23;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.TreeView tvEmpresa;

		private global::Gtk.VBox vbox18;

		private global::Gtk.Label label23;

		private global::Gtk.Label label24;

		private global::Gtk.VBox vbox19;

		private global::Gtk.Label label25;

		private global::Gtk.Label label26;

		private global::Gtk.VBox vbox22;

		private global::Gtk.Label label27;

		private global::Gtk.Label label28;

		private global::Gtk.Label label29;

		private global::Gtk.VBox vbox17;

		private global::Gtk.Entry txtIDEmpresa;

		private global::Gtk.Entry txtNombreEmpresa;

		private global::Gtk.VBox vbox20;

		private global::Gtk.Entry txtNombreComercialEmpresa;

		private global::Gtk.Entry txtDireccionEmpresa;

		private global::Gtk.VBox vbox21;

		private global::Gtk.Entry txtLocalidadEmpresa;

		private global::Gtk.Entry txtCorreoEmpresa;

		private global::Gtk.ComboBox cmbActiva;

		private global::Gtk.HBox hbox24;

		private global::Gtk.Alignment alignment26;

		private global::Gtk.Alignment alignment25;

		private global::Gtk.Button btnEditar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Control_de_Empresa
			this.Name = "Contabilidad_General.Control_de_Empresa";
			this.Title = global::Mono.Unix.Catalog.GetString("Control_de_Empresa");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Control_de_Empresa.Gtk.Container+ContainerChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox19 = new global::Gtk.HBox();
			this.hbox19.Name = "hbox19";
			this.hbox19.Spacing = 6;
			// Container child hbox19.Gtk.Box+BoxChild
			this.alignment24 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment24.Name = "alignment24";
			this.hbox19.Add(this.alignment24);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.alignment24]));
			w1.Position = 0;
			// Container child hbox19.Gtk.Box+BoxChild
			this.alignment23 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment23.Name = "alignment23";
			this.hbox19.Add(this.alignment23);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.alignment23]));
			w2.Position = 1;
			// Container child hbox19.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox19.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox19[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox15.Add(this.hbox19);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox19]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			this.vbox16.BorderWidth = ((uint)(6));
			// Container child vbox16.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Control de Empresa\n");
			this.vbox16.Add(this.label19);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label19]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox20 = new global::Gtk.HBox();
			this.hbox20.Name = "hbox20";
			this.hbox20.Spacing = 6;
			// Container child hbox20.Gtk.Box+BoxChild
			this.hbox22 = new global::Gtk.HBox();
			this.hbox22.Name = "hbox22";
			this.hbox22.Spacing = 6;
			// Container child hbox22.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.Xalign = 1F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID:");
			this.hbox22.Add(this.label22);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.label22]));
			w6.Position = 0;
			// Container child hbox22.Gtk.Box+BoxChild
			this.txtBuscarID = new global::Gtk.Entry();
			this.txtBuscarID.CanFocus = true;
			this.txtBuscarID.Name = "txtBuscarID";
			this.txtBuscarID.IsEditable = true;
			this.txtBuscarID.InvisibleChar = '•';
			this.hbox22.Add(this.txtBuscarID);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.txtBuscarID]));
			w7.Position = 1;
			// Container child hbox22.Gtk.Box+BoxChild
			this.btnBuscarID = new global::Gtk.Button();
			this.btnBuscarID.CanFocus = true;
			this.btnBuscarID.Name = "btnBuscarID";
			this.btnBuscarID.UseUnderline = true;
			this.btnBuscarID.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox22.Add(this.btnBuscarID);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox22[this.btnBuscarID]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox20.Add(this.hbox22);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.hbox22]));
			w9.Position = 0;
			// Container child hbox20.Gtk.Box+BoxChild
			this.hbox21 = new global::Gtk.HBox();
			this.hbox21.Name = "hbox21";
			this.hbox21.Spacing = 6;
			// Container child hbox21.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.Xalign = 1F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por Nombre:");
			this.hbox21.Add(this.label21);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.label21]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox21.Gtk.Box+BoxChild
			this.txtBuscarNombre = new global::Gtk.Entry();
			this.txtBuscarNombre.CanFocus = true;
			this.txtBuscarNombre.Name = "txtBuscarNombre";
			this.txtBuscarNombre.IsEditable = true;
			this.txtBuscarNombre.InvisibleChar = '•';
			this.hbox21.Add(this.txtBuscarNombre);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.txtBuscarNombre]));
			w11.Position = 1;
			// Container child hbox21.Gtk.Box+BoxChild
			this.btnBuscarNombre = new global::Gtk.Button();
			this.btnBuscarNombre.CanFocus = true;
			this.btnBuscarNombre.Name = "btnBuscarNombre";
			this.btnBuscarNombre.UseUnderline = true;
			this.btnBuscarNombre.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox21.Add(this.btnBuscarNombre);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox21[this.btnBuscarNombre]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox20.Add(this.hbox21);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox20[this.hbox21]));
			w13.Position = 1;
			this.vbox16.Add(this.hbox20);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.hbox20]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox16.Gtk.Box+BoxChild
			this.hbox23 = new global::Gtk.HBox();
			this.hbox23.Name = "hbox23";
			this.hbox23.Spacing = 6;
			// Container child hbox23.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.scrolledwindow1.BorderWidth = ((uint)(12));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			this.tvEmpresa = new global::Gtk.TreeView();
			this.tvEmpresa.CanFocus = true;
			this.tvEmpresa.Name = "tvEmpresa";
			this.scrolledwindow1.Add(this.tvEmpresa);
			this.hbox23.Add(this.scrolledwindow1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.scrolledwindow1]));
			w16.Position = 0;
			// Container child hbox23.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.Xalign = 1F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la Empresa:");
			this.vbox18.Add(this.label23);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.label23]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(11));
			// Container child vbox18.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label();
			this.label24.Name = "label24";
			this.label24.Xalign = 1F;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de la Empresa:");
			this.vbox18.Add(this.label24);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.label24]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(3));
			// Container child vbox18.Gtk.Box+BoxChild
			this.vbox19 = new global::Gtk.VBox();
			this.vbox19.Name = "vbox19";
			this.vbox19.Spacing = 6;
			// Container child vbox19.Gtk.Box+BoxChild
			this.label25 = new global::Gtk.Label();
			this.label25.Name = "label25";
			this.label25.Xalign = 1F;
			this.label25.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre Comercial de la Empresa:");
			this.vbox19.Add(this.label25);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.label25]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(9));
			// Container child vbox19.Gtk.Box+BoxChild
			this.label26 = new global::Gtk.Label();
			this.label26.Name = "label26";
			this.label26.Xalign = 1F;
			this.label26.LabelProp = global::Mono.Unix.Catalog.GetString("Direccion de la Empresa:");
			this.vbox19.Add(this.label26);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.label26]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			w20.Padding = ((uint)(2));
			// Container child vbox19.Gtk.Box+BoxChild
			this.vbox22 = new global::Gtk.VBox();
			this.vbox22.Name = "vbox22";
			this.vbox22.Spacing = 6;
			// Container child vbox22.Gtk.Box+BoxChild
			this.label27 = new global::Gtk.Label();
			this.label27.Name = "label27";
			this.label27.Xalign = 1F;
			this.label27.LabelProp = global::Mono.Unix.Catalog.GetString("Localidad de la Empresa:");
			this.vbox22.Add(this.label27);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.label27]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(12));
			// Container child vbox22.Gtk.Box+BoxChild
			this.label28 = new global::Gtk.Label();
			this.label28.Name = "label28";
			this.label28.Xalign = 1F;
			this.label28.LabelProp = global::Mono.Unix.Catalog.GetString("Correo de la Empresa:");
			this.vbox22.Add(this.label28);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.label28]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox22.Gtk.Box+BoxChild
			this.label29 = new global::Gtk.Label();
			this.label29.Name = "label29";
			this.label29.Xalign = 1F;
			this.label29.LabelProp = global::Mono.Unix.Catalog.GetString("Activa:");
			this.vbox22.Add(this.label29);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox22[this.label29]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(9));
			this.vbox19.Add(this.vbox22);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox19[this.vbox22]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox18.Add(this.vbox19);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.vbox19]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.hbox23.Add(this.vbox18);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.vbox18]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox23.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			this.vbox17.BorderWidth = ((uint)(6));
			// Container child vbox17.Gtk.Box+BoxChild
			this.txtIDEmpresa = new global::Gtk.Entry();
			this.txtIDEmpresa.CanFocus = true;
			this.txtIDEmpresa.Name = "txtIDEmpresa";
			this.txtIDEmpresa.IsEditable = true;
			this.txtIDEmpresa.InvisibleChar = '•';
			this.vbox17.Add(this.txtIDEmpresa);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.txtIDEmpresa]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox17.Gtk.Box+BoxChild
			this.txtNombreEmpresa = new global::Gtk.Entry();
			this.txtNombreEmpresa.CanFocus = true;
			this.txtNombreEmpresa.Name = "txtNombreEmpresa";
			this.txtNombreEmpresa.IsEditable = true;
			this.txtNombreEmpresa.InvisibleChar = '•';
			this.vbox17.Add(this.txtNombreEmpresa);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.txtNombreEmpresa]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			w28.Padding = ((uint)(2));
			// Container child vbox17.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.txtNombreComercialEmpresa = new global::Gtk.Entry();
			this.txtNombreComercialEmpresa.CanFocus = true;
			this.txtNombreComercialEmpresa.Name = "txtNombreComercialEmpresa";
			this.txtNombreComercialEmpresa.IsEditable = true;
			this.txtNombreComercialEmpresa.InvisibleChar = '•';
			this.vbox20.Add(this.txtNombreComercialEmpresa);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.txtNombreComercialEmpresa]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox20.Gtk.Box+BoxChild
			this.txtDireccionEmpresa = new global::Gtk.Entry();
			this.txtDireccionEmpresa.CanFocus = true;
			this.txtDireccionEmpresa.Name = "txtDireccionEmpresa";
			this.txtDireccionEmpresa.IsEditable = true;
			this.txtDireccionEmpresa.InvisibleChar = '•';
			this.vbox20.Add(this.txtDireccionEmpresa);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.txtDireccionEmpresa]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(3));
			// Container child vbox20.Gtk.Box+BoxChild
			this.vbox21 = new global::Gtk.VBox();
			this.vbox21.Name = "vbox21";
			this.vbox21.Spacing = 6;
			// Container child vbox21.Gtk.Box+BoxChild
			this.txtLocalidadEmpresa = new global::Gtk.Entry();
			this.txtLocalidadEmpresa.CanFocus = true;
			this.txtLocalidadEmpresa.Name = "txtLocalidadEmpresa";
			this.txtLocalidadEmpresa.IsEditable = true;
			this.txtLocalidadEmpresa.InvisibleChar = '•';
			this.vbox21.Add(this.txtLocalidadEmpresa);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.txtLocalidadEmpresa]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox21.Gtk.Box+BoxChild
			this.txtCorreoEmpresa = new global::Gtk.Entry();
			this.txtCorreoEmpresa.CanFocus = true;
			this.txtCorreoEmpresa.Name = "txtCorreoEmpresa";
			this.txtCorreoEmpresa.IsEditable = true;
			this.txtCorreoEmpresa.InvisibleChar = '•';
			this.vbox21.Add(this.txtCorreoEmpresa);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.txtCorreoEmpresa]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox21.Gtk.Box+BoxChild
			this.cmbActiva = global::Gtk.ComboBox.NewText();
			this.cmbActiva.Name = "cmbActiva";
			this.vbox21.Add(this.cmbActiva);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox21[this.cmbActiva]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			this.vbox20.Add(this.vbox21);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.vbox21]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox17.Add(this.vbox20);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.vbox20]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox23.Add(this.vbox17);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox23[this.vbox17]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			this.vbox16.Add(this.hbox23);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.hbox23]));
			w37.Position = 2;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox15.Add(this.vbox16);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.vbox16]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.hbox24 = new global::Gtk.HBox();
			this.hbox24.Name = "hbox24";
			this.hbox24.Spacing = 6;
			// Container child hbox24.Gtk.Box+BoxChild
			this.alignment26 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment26.Name = "alignment26";
			this.hbox24.Add(this.alignment26);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.alignment26]));
			w39.Position = 0;
			// Container child hbox24.Gtk.Box+BoxChild
			this.alignment25 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment25.Name = "alignment25";
			this.hbox24.Add(this.alignment25);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.alignment25]));
			w40.Position = 1;
			// Container child hbox24.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox24.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox24[this.btnEditar]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			w41.Padding = ((uint)(60));
			this.vbox15.Add(this.hbox24);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.hbox24]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.Add(this.vbox15);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 898;
			this.DefaultHeight = 431;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
