
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Menu_Principal
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Alignment alignment2;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.Button btnSalir;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Frame frame6;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Button btnGenerarEmpresa;

		private global::Gtk.Button btnControlEmpresa;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Button btnControlEmpleados;

		private global::Gtk.Button btnControlUsuarioRol;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Frame frame7;

		private global::Gtk.Alignment GtkAlignment1;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Button btnBalanceGeneral;

		private global::Gtk.Button btnBalanceComprobacion;

		private global::Gtk.Label GtkLabel7;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Frame frame8;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Button btnCatalogoCuentas;

		private global::Gtk.Button btnPeriodosContables;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Button btnLibrosDiarios;

		private global::Gtk.Button btnLibroMayor;

		private global::Gtk.Button btnAsientosContables;

		private global::Gtk.Label GtkLabel13;

		private global::Gtk.Frame frame9;

		private global::Gtk.Alignment GtkAlignment3;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Button btnControlMonedas;

		private global::Gtk.Button btnControlUsuarios;

		private global::Gtk.Label GtkLabel16;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Menu_Principal
			this.Name = "Contabilidad_General.Menu_Principal";
			this.Title = global::Mono.Unix.Catalog.GetString("Menu_Principal");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Menu_Principal.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.hbox4.Add(this.alignment2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment2]));
			w1.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			this.hbox4.Add(this.alignment1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.alignment1]));
			w2.Position = 1;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox4.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox1.Add(this.hbox4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox4]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Menu\n");
			this.vbox1.Add(this.label1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w5.Position = 1;
			w5.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame6 = new global::Gtk.Frame();
			this.frame6.Name = "frame6";
			this.frame6.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame6.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.btnGenerarEmpresa = new global::Gtk.Button();
			this.btnGenerarEmpresa.CanFocus = true;
			this.btnGenerarEmpresa.Name = "btnGenerarEmpresa";
			this.btnGenerarEmpresa.UseUnderline = true;
			this.btnGenerarEmpresa.Label = global::Mono.Unix.Catalog.GetString("Generar Empresa");
			this.vbox10.Add(this.btnGenerarEmpresa);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.btnGenerarEmpresa]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.btnControlEmpresa = new global::Gtk.Button();
			this.btnControlEmpresa.CanFocus = true;
			this.btnControlEmpresa.Name = "btnControlEmpresa";
			this.btnControlEmpresa.UseUnderline = true;
			this.btnControlEmpresa.Label = global::Mono.Unix.Catalog.GetString("Control de Empresa");
			this.vbox10.Add(this.btnControlEmpresa);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.btnControlEmpresa]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.btnControlEmpleados = new global::Gtk.Button();
			this.btnControlEmpleados.CanFocus = true;
			this.btnControlEmpleados.Name = "btnControlEmpleados";
			this.btnControlEmpleados.UseUnderline = true;
			this.btnControlEmpleados.Label = global::Mono.Unix.Catalog.GetString("Control de Empleados");
			this.vbox11.Add(this.btnControlEmpleados);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.btnControlEmpleados]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.btnControlUsuarioRol = new global::Gtk.Button();
			this.btnControlUsuarioRol.CanFocus = true;
			this.btnControlUsuarioRol.Name = "btnControlUsuarioRol";
			this.btnControlUsuarioRol.UseUnderline = true;
			this.btnControlUsuarioRol.Label = global::Mono.Unix.Catalog.GetString("Control de Usuarios con Rol");
			this.vbox11.Add(this.btnControlUsuarioRol);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.btnControlUsuarioRol]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox10.Add(this.vbox11);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.vbox11]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			this.GtkAlignment.Add(this.vbox10);
			this.frame6.Add(this.GtkAlignment);
			this.GtkLabel4 = new global::Gtk.Label();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Control Administrativo                  </b>\n");
			this.GtkLabel4.UseMarkup = true;
			this.frame6.LabelWidget = this.GtkLabel4;
			this.hbox2.Add(this.frame6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame6]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.frame7 = new global::Gtk.Frame();
			this.frame7.Name = "frame7";
			this.frame7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame7.Gtk.Container+ContainerChild
			this.GtkAlignment1 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment1.Name = "GtkAlignment1";
			this.GtkAlignment1.LeftPadding = ((uint)(12));
			// Container child GtkAlignment1.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnBalanceGeneral = new global::Gtk.Button();
			this.btnBalanceGeneral.CanFocus = true;
			this.btnBalanceGeneral.Name = "btnBalanceGeneral";
			this.btnBalanceGeneral.UseUnderline = true;
			this.btnBalanceGeneral.Label = global::Mono.Unix.Catalog.GetString("Balance General");
			this.vbox8.Add(this.btnBalanceGeneral);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.btnBalanceGeneral]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.btnBalanceComprobacion = new global::Gtk.Button();
			this.btnBalanceComprobacion.CanFocus = true;
			this.btnBalanceComprobacion.Name = "btnBalanceComprobacion";
			this.btnBalanceComprobacion.UseUnderline = true;
			this.btnBalanceComprobacion.Label = global::Mono.Unix.Catalog.GetString("Balance de Comprobacion");
			this.vbox8.Add(this.btnBalanceComprobacion);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.btnBalanceComprobacion]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.GtkAlignment1.Add(this.vbox8);
			this.frame7.Add(this.GtkAlignment1);
			this.GtkLabel7 = new global::Gtk.Label();
			this.GtkLabel7.Name = "GtkLabel7";
			this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Reportes                                             </b>\n");
			this.GtkLabel7.UseMarkup = true;
			this.frame7.LabelWidget = this.GtkLabel7;
			this.hbox2.Add(this.frame7);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.frame7]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			this.hbox1.Add(this.hbox2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.hbox2]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame8 = new global::Gtk.Frame();
			this.frame8.Name = "frame8";
			this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame8.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.btnCatalogoCuentas = new global::Gtk.Button();
			this.btnCatalogoCuentas.CanFocus = true;
			this.btnCatalogoCuentas.Name = "btnCatalogoCuentas";
			this.btnCatalogoCuentas.UseUnderline = true;
			this.btnCatalogoCuentas.Label = global::Mono.Unix.Catalog.GetString("Control de Catalogos de Cuentas");
			this.vbox12.Add(this.btnCatalogoCuentas);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.btnCatalogoCuentas]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.btnPeriodosContables = new global::Gtk.Button();
			this.btnPeriodosContables.CanFocus = true;
			this.btnPeriodosContables.Name = "btnPeriodosContables";
			this.btnPeriodosContables.UseUnderline = true;
			this.btnPeriodosContables.Label = global::Mono.Unix.Catalog.GetString("Control de Periodos Contables");
			this.vbox12.Add(this.btnPeriodosContables);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.btnPeriodosContables]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.btnLibrosDiarios = new global::Gtk.Button();
			this.btnLibrosDiarios.CanFocus = true;
			this.btnLibrosDiarios.Name = "btnLibrosDiarios";
			this.btnLibrosDiarios.UseUnderline = true;
			this.btnLibrosDiarios.Label = global::Mono.Unix.Catalog.GetString("Control de Libros Diarios");
			this.vbox13.Add(this.btnLibrosDiarios);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.btnLibrosDiarios]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.btnLibroMayor = new global::Gtk.Button();
			this.btnLibroMayor.CanFocus = true;
			this.btnLibroMayor.Name = "btnLibroMayor";
			this.btnLibroMayor.UseUnderline = true;
			this.btnLibroMayor.Label = global::Mono.Unix.Catalog.GetString("Control de Libro Mayor");
			this.vbox13.Add(this.btnLibroMayor);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.btnLibroMayor]));
			w24.Position = 1;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.btnAsientosContables = new global::Gtk.Button();
			this.btnAsientosContables.CanFocus = true;
			this.btnAsientosContables.Name = "btnAsientosContables";
			this.btnAsientosContables.UseUnderline = true;
			this.btnAsientosContables.Label = global::Mono.Unix.Catalog.GetString("Control de Asientos Contables");
			this.vbox13.Add(this.btnAsientosContables);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.btnAsientosContables]));
			w25.Position = 2;
			w25.Expand = false;
			w25.Fill = false;
			this.vbox12.Add(this.vbox13);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox13]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			this.GtkAlignment2.Add(this.vbox12);
			this.frame8.Add(this.GtkAlignment2);
			this.GtkLabel13 = new global::Gtk.Label();
			this.GtkLabel13.Name = "GtkLabel13";
			this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString("\n<b>Control de Contabilidad       </b>\n");
			this.GtkLabel13.UseMarkup = true;
			this.frame8.LabelWidget = this.GtkLabel13;
			this.hbox3.Add(this.frame8);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame8]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.frame9 = new global::Gtk.Frame();
			this.frame9.Name = "frame9";
			this.frame9.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame9.Gtk.Container+ContainerChild
			this.GtkAlignment3 = new global::Gtk.Alignment(0F, 0F, 1F, 1F);
			this.GtkAlignment3.Name = "GtkAlignment3";
			this.GtkAlignment3.LeftPadding = ((uint)(12));
			// Container child GtkAlignment3.Gtk.Container+ContainerChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.btnControlMonedas = new global::Gtk.Button();
			this.btnControlMonedas.CanFocus = true;
			this.btnControlMonedas.Name = "btnControlMonedas";
			this.btnControlMonedas.UseUnderline = true;
			this.btnControlMonedas.Label = global::Mono.Unix.Catalog.GetString("Control de Monedas");
			this.vbox9.Add(this.btnControlMonedas);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.btnControlMonedas]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.btnControlUsuarios = new global::Gtk.Button();
			this.btnControlUsuarios.CanFocus = true;
			this.btnControlUsuarios.Name = "btnControlUsuarios";
			this.btnControlUsuarios.UseUnderline = true;
			this.btnControlUsuarios.Label = global::Mono.Unix.Catalog.GetString("Control de Usuarios");
			this.vbox9.Add(this.btnControlUsuarios);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.btnControlUsuarios]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.GtkAlignment3.Add(this.vbox9);
			this.frame9.Add(this.GtkAlignment3);
			this.GtkLabel16 = new global::Gtk.Label();
			this.GtkLabel16.Name = "GtkLabel16";
			this.GtkLabel16.LabelProp = global::Mono.Unix.Catalog.GetString("\n<b>Mantenimiento                                   </b>\n");
			this.GtkLabel16.UseMarkup = true;
			this.frame9.LabelWidget = this.GtkLabel16;
			this.hbox3.Add(this.frame9);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.frame9]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox1.Add(this.hbox3);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w35.Position = 3;
			w35.Expand = false;
			w35.Fill = false;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 517;
			this.DefaultHeight = 504;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
			this.btnGenerarEmpresa.Clicked += new global::System.EventHandler(this.OnBtnGenerarEmpresaClicked);
			this.btnControlEmpresa.Clicked += new global::System.EventHandler(this.OnBtnControlEmpresaClicked);
			this.btnControlEmpleados.Clicked += new global::System.EventHandler(this.OnBtnControlEmpleadosClicked);
			this.btnControlUsuarioRol.Clicked += new global::System.EventHandler(this.OnBtnControlUsuarioRolClicked);
			this.btnBalanceGeneral.Clicked += new global::System.EventHandler(this.OnBtnBalanceGeneralClicked);
			this.btnBalanceComprobacion.Clicked += new global::System.EventHandler(this.OnBtnBalanceComprobacionClicked);
			this.btnCatalogoCuentas.Clicked += new global::System.EventHandler(this.OnBtnCatalogoCuentasClicked);
			this.btnPeriodosContables.Clicked += new global::System.EventHandler(this.OnBtnPeriodosContablesClicked);
			this.btnLibrosDiarios.Clicked += new global::System.EventHandler(this.OnBtnLibrosDiariosClicked);
			this.btnLibroMayor.Clicked += new global::System.EventHandler(this.OnBtnLibroMayorClicked);
			this.btnAsientosContables.Clicked += new global::System.EventHandler(this.OnBtnAsientosContablesClicked);
			this.btnControlMonedas.Clicked += new global::System.EventHandler(this.OnBtnControlMonedasClicked);
			this.btnControlUsuarios.Clicked += new global::System.EventHandler(this.OnBtnControlUsuariosClicked);
		}
	}
}
