
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Control_de_Libro_Diario
	{
		private global::Gtk.VBox vbox11;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Alignment alignment10;

		private global::Gtk.Alignment alignment9;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Label label15;

		private global::Gtk.HBox hbox10;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label14;

		private global::Gtk.Entry txtBuscarID;

		private global::Gtk.Button btnBuscarID;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label13;

		private global::Gtk.Entry txtBuscarFecha;

		private global::Gtk.Button btnBuscarFecha;

		private global::Gtk.HBox hbox11;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.TreeView treeview2;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.Label label10;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Label label18;

		private global::Gtk.Label label19;

		private global::Gtk.Label label9;

		private global::Gtk.VBox vbox18;

		private global::Gtk.Label label21;

		private global::Gtk.VBox vbox20;

		private global::Gtk.Label label22;

		private global::Gtk.Label label23;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Entry txtIDLibroDiario;

		private global::Gtk.Entry txtFechaLibroDiario;

		private global::Gtk.Entry txtConceptoMovimiento;

		private global::Gtk.Entry txtTotalDebe;

		private global::Gtk.VBox vbox15;

		private global::Gtk.Entry txtTotalHaber;

		private global::Gtk.ComboBox cmbActivo;

		private global::Gtk.ComboBox cmbIDAsiento;

		private global::Gtk.VBox vbox17;

		private global::Gtk.ComboBox cmIDCatalogoCuentas;

		private global::Gtk.ComboBox cmbIDPeriodoContable;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Alignment alignment12;

		private global::Gtk.Alignment alignment11;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Button btnNuevo;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnEditar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Control_de_Libro_Diario
			this.Name = "Contabilidad_General.Control_de_Libro_Diario";
			this.Title = global::Mono.Unix.Catalog.GetString("Control_de_Libro_Diario");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Control_de_Libro_Diario.Gtk.Container+ContainerChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			this.hbox8.Add(this.alignment10);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment10]));
			w1.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.hbox8.Add(this.alignment9);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment9]));
			w2.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox8.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox11.Add(this.hbox8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			this.vbox12.BorderWidth = ((uint)(9));
			// Container child vbox12.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("Control del Libro Diario\n");
			this.vbox12.Add(this.label15);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.label15]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID:");
			this.hbox13.Add(this.label14);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label14]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.txtBuscarID = new global::Gtk.Entry();
			this.txtBuscarID.CanFocus = true;
			this.txtBuscarID.Name = "txtBuscarID";
			this.txtBuscarID.IsEditable = true;
			this.txtBuscarID.InvisibleChar = '•';
			this.hbox13.Add(this.txtBuscarID);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.txtBuscarID]));
			w7.Position = 1;
			// Container child hbox13.Gtk.Box+BoxChild
			this.btnBuscarID = new global::Gtk.Button();
			this.btnBuscarID.CanFocus = true;
			this.btnBuscarID.Name = "btnBuscarID";
			this.btnBuscarID.UseUnderline = true;
			this.btnBuscarID.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox13.Add(this.btnBuscarID);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.btnBuscarID]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox10.Add(this.hbox13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.hbox13]));
			w9.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por Fecha:");
			this.hbox12.Add(this.label13);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label13]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.txtBuscarFecha = new global::Gtk.Entry();
			this.txtBuscarFecha.CanFocus = true;
			this.txtBuscarFecha.Name = "txtBuscarFecha";
			this.txtBuscarFecha.IsEditable = true;
			this.txtBuscarFecha.InvisibleChar = '•';
			this.hbox12.Add(this.txtBuscarFecha);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.txtBuscarFecha]));
			w11.Position = 1;
			// Container child hbox12.Gtk.Box+BoxChild
			this.btnBuscarFecha = new global::Gtk.Button();
			this.btnBuscarFecha.CanFocus = true;
			this.btnBuscarFecha.Name = "btnBuscarFecha";
			this.btnBuscarFecha.UseUnderline = true;
			this.btnBuscarFecha.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox12.Add(this.btnBuscarFecha);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.btnBuscarFecha]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox10.Add(this.hbox12);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.hbox12]));
			w13.Position = 1;
			this.vbox12.Add(this.hbox10);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox10]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.scrolledwindow2.Add(this.treeview2);
			this.hbox11.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.scrolledwindow2]));
			w16.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.Name = "label16";
			this.label16.Xalign = 1F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Libro Diario:");
			this.vbox14.Add(this.label16);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label16]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(11));
			// Container child vbox14.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha del Libro Diario:");
			this.vbox14.Add(this.label17);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label17]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(6));
			// Container child vbox14.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.Xalign = 1F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Concepto del Movimiento:");
			this.vbox14.Add(this.label10);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label10]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(7));
			// Container child vbox14.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Total Debe:");
			this.vbox16.Add(this.label18);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label18]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			w20.Padding = ((uint)(15));
			// Container child vbox16.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.Xalign = 1F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Total Haber:");
			this.vbox16.Add(this.label19);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label19]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(7));
			// Container child vbox16.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.Xalign = 1F;
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Activo:");
			this.vbox16.Add(this.label9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label9]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			w22.Padding = ((uint)(8));
			// Container child vbox16.Gtk.Box+BoxChild
			this.vbox18 = new global::Gtk.VBox();
			this.vbox18.Name = "vbox18";
			this.vbox18.Spacing = 6;
			// Container child vbox18.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.Xalign = 1F;
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Asiento Contable:");
			this.vbox18.Add(this.label21);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.label21]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(8));
			// Container child vbox18.Gtk.Box+BoxChild
			this.vbox20 = new global::Gtk.VBox();
			this.vbox20.Name = "vbox20";
			this.vbox20.Spacing = 6;
			// Container child vbox20.Gtk.Box+BoxChild
			this.label22 = new global::Gtk.Label();
			this.label22.Name = "label22";
			this.label22.Xalign = 1F;
			this.label22.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Catalogo de Cuentas:");
			this.vbox20.Add(this.label22);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.label22]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(7));
			// Container child vbox20.Gtk.Box+BoxChild
			this.label23 = new global::Gtk.Label();
			this.label23.Name = "label23";
			this.label23.Xalign = 1F;
			this.label23.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Periodo Contable:");
			this.vbox20.Add(this.label23);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox20[this.label23]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			w25.Padding = ((uint)(18));
			this.vbox18.Add(this.vbox20);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox18[this.vbox20]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			w26.Padding = ((uint)(6));
			this.vbox16.Add(this.vbox18);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.vbox18]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			this.vbox14.Add(this.vbox16);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.vbox16]));
			w28.Position = 3;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox11.Add(this.vbox14);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox14]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.txtIDLibroDiario = new global::Gtk.Entry();
			this.txtIDLibroDiario.CanFocus = true;
			this.txtIDLibroDiario.Name = "txtIDLibroDiario";
			this.txtIDLibroDiario.IsEditable = true;
			this.txtIDLibroDiario.InvisibleChar = '•';
			this.vbox13.Add(this.txtIDLibroDiario);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.txtIDLibroDiario]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(4));
			// Container child vbox13.Gtk.Box+BoxChild
			this.txtFechaLibroDiario = new global::Gtk.Entry();
			this.txtFechaLibroDiario.CanFocus = true;
			this.txtFechaLibroDiario.Name = "txtFechaLibroDiario";
			this.txtFechaLibroDiario.IsEditable = true;
			this.txtFechaLibroDiario.InvisibleChar = '•';
			this.vbox13.Add(this.txtFechaLibroDiario);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.txtFechaLibroDiario]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			w31.Padding = ((uint)(4));
			// Container child vbox13.Gtk.Box+BoxChild
			this.txtConceptoMovimiento = new global::Gtk.Entry();
			this.txtConceptoMovimiento.CanFocus = true;
			this.txtConceptoMovimiento.Name = "txtConceptoMovimiento";
			this.txtConceptoMovimiento.IsEditable = true;
			this.txtConceptoMovimiento.InvisibleChar = '•';
			this.vbox13.Add(this.txtConceptoMovimiento);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.txtConceptoMovimiento]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.txtTotalDebe = new global::Gtk.Entry();
			this.txtTotalDebe.CanFocus = true;
			this.txtTotalDebe.Name = "txtTotalDebe";
			this.txtTotalDebe.IsEditable = true;
			this.txtTotalDebe.InvisibleChar = '•';
			this.vbox13.Add(this.txtTotalDebe);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.txtTotalDebe]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			w33.Padding = ((uint)(9));
			// Container child vbox13.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.txtTotalHaber = new global::Gtk.Entry();
			this.txtTotalHaber.CanFocus = true;
			this.txtTotalHaber.Name = "txtTotalHaber";
			this.txtTotalHaber.IsEditable = true;
			this.txtTotalHaber.InvisibleChar = '•';
			this.vbox15.Add(this.txtTotalHaber);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.txtTotalHaber]));
			w34.Position = 0;
			w34.Expand = false;
			w34.Fill = false;
			w34.Padding = ((uint)(4));
			// Container child vbox15.Gtk.Box+BoxChild
			this.cmbActivo = global::Gtk.ComboBox.NewText();
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbActivo.Name = "cmbActivo";
			this.cmbActivo.Active = 0;
			this.vbox15.Add(this.cmbActivo);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.cmbActivo]));
			w35.Position = 1;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.cmbIDAsiento = global::Gtk.ComboBox.NewText();
			this.cmbIDAsiento.Name = "cmbIDAsiento";
			this.vbox15.Add(this.cmbIDAsiento);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.cmbIDAsiento]));
			w36.Position = 2;
			w36.Expand = false;
			w36.Fill = false;
			w36.Padding = ((uint)(4));
			// Container child vbox15.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.cmIDCatalogoCuentas = global::Gtk.ComboBox.NewText();
			this.cmIDCatalogoCuentas.Name = "cmIDCatalogoCuentas";
			this.vbox17.Add(this.cmIDCatalogoCuentas);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.cmIDCatalogoCuentas]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			w37.Padding = ((uint)(4));
			// Container child vbox17.Gtk.Box+BoxChild
			this.cmbIDPeriodoContable = global::Gtk.ComboBox.NewText();
			this.cmbIDPeriodoContable.Name = "cmbIDPeriodoContable";
			this.vbox17.Add(this.cmbIDPeriodoContable);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.cmbIDPeriodoContable]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			w38.Padding = ((uint)(4));
			this.vbox15.Add(this.vbox17);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.vbox17]));
			w39.Position = 3;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox13.Add(this.vbox15);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.vbox15]));
			w40.Position = 4;
			w40.Expand = false;
			w40.Fill = false;
			this.hbox11.Add(this.vbox13);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.vbox13]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.vbox12.Add(this.hbox11);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.hbox11]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox11.Add(this.vbox12);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.vbox12]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox11.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.hbox9.Add(this.alignment12);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.alignment12]));
			w44.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			this.hbox9.Add(this.alignment11);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.alignment11]));
			w45.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnNuevo = new global::Gtk.Button();
			this.btnNuevo.CanFocus = true;
			this.btnNuevo.Name = "btnNuevo";
			this.btnNuevo.UseUnderline = true;
			this.btnNuevo.BorderWidth = ((uint)(6));
			this.btnNuevo.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.hbox14.Add(this.btnNuevo);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnNuevo]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.BorderWidth = ((uint)(6));
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox14.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnAgregar]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.BorderWidth = ((uint)(6));
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox14.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnEditar]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox9.Add(this.hbox14);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox14]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			this.vbox11.Add(this.hbox9);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.hbox9]));
			w50.Position = 2;
			w50.Expand = false;
			w50.Fill = false;
			this.Add(this.vbox11);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 848;
			this.DefaultHeight = 592;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
