
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Control_de_Usuarios
	{
		private global::Gtk.VBox vbox46;

		private global::Gtk.HBox hbox48;

		private global::Gtk.Alignment alignment42;

		private global::Gtk.Alignment alignment41;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox47;

		private global::Gtk.Label label61;

		private global::Gtk.HBox hbox51;

		private global::Gtk.HBox hbox53;

		private global::Gtk.Label label63;

		private global::Gtk.Entry txtBuscarID;

		private global::Gtk.Button btnBuscarID;

		private global::Gtk.HBox hbox52;

		private global::Gtk.Label label62;

		private global::Gtk.Entry txtBuscarUsuario;

		private global::Gtk.Button btnBuscarUsuario;

		private global::Gtk.HBox hbox50;

		private global::Gtk.ScrolledWindow scrolledwindow5;

		private global::Gtk.TreeView tvUsuarios;

		private global::Gtk.VBox vbox48;

		private global::Gtk.Label label64;

		private global::Gtk.Label label65;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.VBox vbox51;

		private global::Gtk.Label label66;

		private global::Gtk.Label label67;

		private global::Gtk.Label label68;

		private global::Gtk.VBox vbox49;

		private global::Gtk.Entry txtIDUsuario;

		private global::Gtk.Entry txtUsuario;

		private global::Gtk.Entry txtContrasenya;

		private global::Gtk.Entry txtFechaCreacion;

		private global::Gtk.VBox vbox50;

		private global::Gtk.ComboBox cmbActivo;

		private global::Gtk.ComboBox cmbIDEmpleado;

		private global::Gtk.ComboBox cmbIDEmpresa;

		private global::Gtk.HBox hbox49;

		private global::Gtk.Alignment alignment40;

		private global::Gtk.Alignment alignment39;

		private global::Gtk.HBox hbox54;

		private global::Gtk.Button btnNuevo;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnEditar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Control_de_Usuarios
			this.Name = "Contabilidad_General.Control_de_Usuarios";
			this.Title = global::Mono.Unix.Catalog.GetString("Control_de_Usuarios");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Control_de_Usuarios.Gtk.Container+ContainerChild
			this.vbox46 = new global::Gtk.VBox();
			this.vbox46.Name = "vbox46";
			this.vbox46.Spacing = 6;
			// Container child vbox46.Gtk.Box+BoxChild
			this.hbox48 = new global::Gtk.HBox();
			this.hbox48.Name = "hbox48";
			this.hbox48.Spacing = 6;
			// Container child hbox48.Gtk.Box+BoxChild
			this.alignment42 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment42.Name = "alignment42";
			this.hbox48.Add(this.alignment42);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.alignment42]));
			w1.Position = 0;
			// Container child hbox48.Gtk.Box+BoxChild
			this.alignment41 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment41.Name = "alignment41";
			this.hbox48.Add(this.alignment41);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.alignment41]));
			w2.Position = 1;
			// Container child hbox48.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox48.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox48[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox46.Add(this.hbox48);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox46[this.hbox48]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox46.Gtk.Box+BoxChild
			this.vbox47 = new global::Gtk.VBox();
			this.vbox47.Name = "vbox47";
			this.vbox47.Spacing = 6;
			this.vbox47.BorderWidth = ((uint)(9));
			// Container child vbox47.Gtk.Box+BoxChild
			this.label61 = new global::Gtk.Label();
			this.label61.Name = "label61";
			this.label61.LabelProp = global::Mono.Unix.Catalog.GetString("Control de Usuarios");
			this.vbox47.Add(this.label61);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox47[this.label61]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox47.Gtk.Box+BoxChild
			this.hbox51 = new global::Gtk.HBox();
			this.hbox51.Name = "hbox51";
			this.hbox51.Spacing = 6;
			// Container child hbox51.Gtk.Box+BoxChild
			this.hbox53 = new global::Gtk.HBox();
			this.hbox53.Name = "hbox53";
			this.hbox53.Spacing = 6;
			// Container child hbox53.Gtk.Box+BoxChild
			this.label63 = new global::Gtk.Label();
			this.label63.Name = "label63";
			this.label63.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por  Id del Usuario:");
			this.hbox53.Add(this.label63);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.label63]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox53.Gtk.Box+BoxChild
			this.txtBuscarID = new global::Gtk.Entry();
			this.txtBuscarID.CanFocus = true;
			this.txtBuscarID.Name = "txtBuscarID";
			this.txtBuscarID.IsEditable = true;
			this.txtBuscarID.InvisibleChar = '•';
			this.hbox53.Add(this.txtBuscarID);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.txtBuscarID]));
			w7.Position = 1;
			// Container child hbox53.Gtk.Box+BoxChild
			this.btnBuscarID = new global::Gtk.Button();
			this.btnBuscarID.CanFocus = true;
			this.btnBuscarID.Name = "btnBuscarID";
			this.btnBuscarID.UseUnderline = true;
			this.btnBuscarID.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox53.Add(this.btnBuscarID);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox53[this.btnBuscarID]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox51.Add(this.hbox53);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.hbox53]));
			w9.Position = 0;
			// Container child hbox51.Gtk.Box+BoxChild
			this.hbox52 = new global::Gtk.HBox();
			this.hbox52.Name = "hbox52";
			this.hbox52.Spacing = 6;
			// Container child hbox52.Gtk.Box+BoxChild
			this.label62 = new global::Gtk.Label();
			this.label62.Name = "label62";
			this.label62.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por Usuario:");
			this.hbox52.Add(this.label62);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.label62]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox52.Gtk.Box+BoxChild
			this.txtBuscarUsuario = new global::Gtk.Entry();
			this.txtBuscarUsuario.CanFocus = true;
			this.txtBuscarUsuario.Name = "txtBuscarUsuario";
			this.txtBuscarUsuario.IsEditable = true;
			this.txtBuscarUsuario.InvisibleChar = '•';
			this.hbox52.Add(this.txtBuscarUsuario);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.txtBuscarUsuario]));
			w11.Position = 1;
			// Container child hbox52.Gtk.Box+BoxChild
			this.btnBuscarUsuario = new global::Gtk.Button();
			this.btnBuscarUsuario.CanFocus = true;
			this.btnBuscarUsuario.Name = "btnBuscarUsuario";
			this.btnBuscarUsuario.UseUnderline = true;
			this.btnBuscarUsuario.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox52.Add(this.btnBuscarUsuario);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox52[this.btnBuscarUsuario]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox51.Add(this.hbox52);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox51[this.hbox52]));
			w13.Position = 1;
			this.vbox47.Add(this.hbox51);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox47[this.hbox51]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox47.Gtk.Box+BoxChild
			this.hbox50 = new global::Gtk.HBox();
			this.hbox50.Name = "hbox50";
			this.hbox50.Spacing = 6;
			// Container child hbox50.Gtk.Box+BoxChild
			this.scrolledwindow5 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow5.CanFocus = true;
			this.scrolledwindow5.Name = "scrolledwindow5";
			this.scrolledwindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow5.Gtk.Container+ContainerChild
			this.tvUsuarios = new global::Gtk.TreeView();
			this.tvUsuarios.CanFocus = true;
			this.tvUsuarios.Name = "tvUsuarios";
			this.scrolledwindow5.Add(this.tvUsuarios);
			this.hbox50.Add(this.scrolledwindow5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox50[this.scrolledwindow5]));
			w16.Position = 0;
			// Container child hbox50.Gtk.Box+BoxChild
			this.vbox48 = new global::Gtk.VBox();
			this.vbox48.Name = "vbox48";
			this.vbox48.Spacing = 6;
			// Container child vbox48.Gtk.Box+BoxChild
			this.label64 = new global::Gtk.Label();
			this.label64.Name = "label64";
			this.label64.Xalign = 1F;
			this.label64.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Usuario:");
			this.vbox48.Add(this.label64);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.label64]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(13));
			// Container child vbox48.Gtk.Box+BoxChild
			this.label65 = new global::Gtk.Label();
			this.label65.Name = "label65";
			this.label65.Xalign = 1F;
			this.label65.LabelProp = global::Mono.Unix.Catalog.GetString("Usuario:");
			this.vbox48.Add(this.label65);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.label65]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox48.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.Xalign = 1F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Contraseña:");
			this.vbox48.Add(this.label2);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.label2]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(11));
			// Container child vbox48.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.Xalign = 1F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Fecha de Creacion:");
			this.vbox48.Add(this.label3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.label3]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			w20.Padding = ((uint)(5));
			// Container child vbox48.Gtk.Box+BoxChild
			this.vbox51 = new global::Gtk.VBox();
			this.vbox51.Name = "vbox51";
			this.vbox51.Spacing = 6;
			// Container child vbox51.Gtk.Box+BoxChild
			this.label66 = new global::Gtk.Label();
			this.label66.Name = "label66";
			this.label66.Xalign = 1F;
			this.label66.LabelProp = global::Mono.Unix.Catalog.GetString("Activo:");
			this.vbox51.Add(this.label66);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox51[this.label66]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			w21.Padding = ((uint)(13));
			// Container child vbox51.Gtk.Box+BoxChild
			this.label67 = new global::Gtk.Label();
			this.label67.Name = "label67";
			this.label67.Xalign = 1F;
			this.label67.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Empleado:");
			this.vbox51.Add(this.label67);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox51[this.label67]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox51.Gtk.Box+BoxChild
			this.label68 = new global::Gtk.Label();
			this.label68.Name = "label68";
			this.label68.Xalign = 1F;
			this.label68.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la Empresa:");
			this.vbox51.Add(this.label68);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox51[this.label68]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(15));
			this.vbox48.Add(this.vbox51);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox48[this.vbox51]));
			w24.Position = 4;
			w24.Expand = false;
			w24.Fill = false;
			this.hbox50.Add(this.vbox48);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox50[this.vbox48]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox50.Gtk.Box+BoxChild
			this.vbox49 = new global::Gtk.VBox();
			this.vbox49.Name = "vbox49";
			this.vbox49.Spacing = 6;
			// Container child vbox49.Gtk.Box+BoxChild
			this.txtIDUsuario = new global::Gtk.Entry();
			this.txtIDUsuario.CanFocus = true;
			this.txtIDUsuario.Name = "txtIDUsuario";
			this.txtIDUsuario.IsEditable = true;
			this.txtIDUsuario.InvisibleChar = '•';
			this.vbox49.Add(this.txtIDUsuario);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.txtIDUsuario]));
			w26.Position = 0;
			w26.Expand = false;
			w26.Fill = false;
			w26.Padding = ((uint)(3));
			// Container child vbox49.Gtk.Box+BoxChild
			this.txtUsuario = new global::Gtk.Entry();
			this.txtUsuario.CanFocus = true;
			this.txtUsuario.Name = "txtUsuario";
			this.txtUsuario.IsEditable = true;
			this.txtUsuario.InvisibleChar = '•';
			this.vbox49.Add(this.txtUsuario);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.txtUsuario]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			w27.Padding = ((uint)(2));
			// Container child vbox49.Gtk.Box+BoxChild
			this.txtContrasenya = new global::Gtk.Entry();
			this.txtContrasenya.CanFocus = true;
			this.txtContrasenya.Name = "txtContrasenya";
			this.txtContrasenya.IsEditable = true;
			this.txtContrasenya.InvisibleChar = '•';
			this.vbox49.Add(this.txtContrasenya);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.txtContrasenya]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			w28.Padding = ((uint)(3));
			// Container child vbox49.Gtk.Box+BoxChild
			this.txtFechaCreacion = new global::Gtk.Entry();
			this.txtFechaCreacion.CanFocus = true;
			this.txtFechaCreacion.Name = "txtFechaCreacion";
			this.txtFechaCreacion.IsEditable = true;
			this.txtFechaCreacion.InvisibleChar = '•';
			this.vbox49.Add(this.txtFechaCreacion);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.txtFechaCreacion]));
			w29.Position = 3;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox49.Gtk.Box+BoxChild
			this.vbox50 = new global::Gtk.VBox();
			this.vbox50.Name = "vbox50";
			this.vbox50.Spacing = 6;
			// Container child vbox50.Gtk.Box+BoxChild
			this.cmbActivo = global::Gtk.ComboBox.NewText();
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbActivo.Name = "cmbActivo";
			this.vbox50.Add(this.cmbActivo);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox50[this.cmbActivo]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(6));
			// Container child vbox50.Gtk.Box+BoxChild
			this.cmbIDEmpleado = global::Gtk.ComboBox.NewText();
			this.cmbIDEmpleado.Name = "cmbIDEmpleado";
			this.vbox50.Add(this.cmbIDEmpleado);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox50[this.cmbIDEmpleado]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			w31.Padding = ((uint)(2));
			// Container child vbox50.Gtk.Box+BoxChild
			this.cmbIDEmpresa = global::Gtk.ComboBox.NewText();
			this.cmbIDEmpresa.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbIDEmpresa.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbIDEmpresa.Name = "cmbIDEmpresa";
			this.vbox50.Add(this.cmbIDEmpresa);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox50[this.cmbIDEmpresa]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			w32.Padding = ((uint)(2));
			this.vbox49.Add(this.vbox50);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox49[this.vbox50]));
			w33.Position = 4;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox50.Add(this.vbox49);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox50[this.vbox49]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox47.Add(this.hbox50);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox47[this.hbox50]));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			this.vbox46.Add(this.vbox47);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox46[this.vbox47]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child vbox46.Gtk.Box+BoxChild
			this.hbox49 = new global::Gtk.HBox();
			this.hbox49.Name = "hbox49";
			this.hbox49.Spacing = 6;
			// Container child hbox49.Gtk.Box+BoxChild
			this.alignment40 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment40.Name = "alignment40";
			this.hbox49.Add(this.alignment40);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.alignment40]));
			w37.Position = 0;
			// Container child hbox49.Gtk.Box+BoxChild
			this.alignment39 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment39.Name = "alignment39";
			this.hbox49.Add(this.alignment39);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.alignment39]));
			w38.Position = 1;
			// Container child hbox49.Gtk.Box+BoxChild
			this.hbox54 = new global::Gtk.HBox();
			this.hbox54.Name = "hbox54";
			this.hbox54.Spacing = 6;
			// Container child hbox54.Gtk.Box+BoxChild
			this.btnNuevo = new global::Gtk.Button();
			this.btnNuevo.CanFocus = true;
			this.btnNuevo.Name = "btnNuevo";
			this.btnNuevo.UseUnderline = true;
			this.btnNuevo.BorderWidth = ((uint)(3));
			this.btnNuevo.Label = global::Mono.Unix.Catalog.GetString("Nuevo");
			this.hbox54.Add(this.btnNuevo);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox54[this.btnNuevo]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			// Container child hbox54.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.BorderWidth = ((uint)(3));
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox54.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox54[this.btnAgregar]));
			w40.Position = 1;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox54.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.BorderWidth = ((uint)(3));
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox54.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox54[this.btnEditar]));
			w41.Position = 2;
			w41.Expand = false;
			w41.Fill = false;
			this.hbox49.Add(this.hbox54);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox49[this.hbox54]));
			w42.Position = 2;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox46.Add(this.hbox49);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox46[this.hbox49]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.Add(this.vbox46);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 793;
			this.DefaultHeight = 446;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
