
// This file has been generated by the GUI designer. Do not modify.
namespace Contabilidad_General
{
	public partial class Control_de_Catalogo_de_Cuentas
	{
		private global::Gtk.VBox vbox8;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Alignment alignment6;

		private global::Gtk.Alignment alignment5;

		private global::Gtk.Button btnSalir;

		private global::Gtk.Label label10;

		private global::Gtk.VBox vbox9;

		private global::Gtk.HBox hbox9;

		private global::Gtk.HBox hbox13;

		private global::Gtk.Label label12;

		private global::Gtk.Entry txtBuscarID;

		private global::Gtk.Button btnBuscarID;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Label label11;

		private global::Gtk.Entry txtBuscarNombre;

		private global::Gtk.Button btnBuscarNombre;

		private global::Gtk.HBox hbox10;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.TreeView tvCatalogoCuentas;

		private global::Gtk.VBox vbox14;

		private global::Gtk.Label label13;

		private global::Gtk.Label label14;

		private global::Gtk.VBox vbox15;

		private global::Gtk.VBox vbox16;

		private global::Gtk.Label label17;

		private global::Gtk.Label label18;

		private global::Gtk.VBox vbox17;

		private global::Gtk.Label label19;

		private global::Gtk.Label label20;

		private global::Gtk.Label label5;

		private global::Gtk.Label label4;

		private global::Gtk.VBox vbox10;

		private global::Gtk.Entry txtIDCatalogoCuentas;

		private global::Gtk.VBox vbox11;

		private global::Gtk.Entry txtNumeroCuenta;

		private global::Gtk.VBox vbox12;

		private global::Gtk.Entry txtNombreCuenta;

		private global::Gtk.VBox vbox13;

		private global::Gtk.Entry txtDescripcionCuenta;

		private global::Gtk.ComboBox cmbActivo;

		private global::Gtk.Entry txtPaisCuenta;

		private global::Gtk.Entry cmbIDCuentaPadre;

		private global::Gtk.ComboBox cmbIDNaturalezaCuenta;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Alignment alignment8;

		private global::Gtk.Alignment alignment7;

		private global::Gtk.HBox hbox14;

		private global::Gtk.Button btnNueva;

		private global::Gtk.Button btnAgregar;

		private global::Gtk.Button btnEditar;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Contabilidad_General.Control_de_Catalogo_de_Cuentas
			this.Name = "Contabilidad_General.Control_de_Catalogo_de_Cuentas";
			this.Title = global::Mono.Unix.Catalog.GetString("Control_de_Catalogo_de_Cuentas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Contabilidad_General.Control_de_Catalogo_de_Cuentas.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.hbox8.Add(this.alignment6);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment6]));
			w1.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.hbox8.Add(this.alignment5);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.alignment5]));
			w2.Position = 1;
			// Container child hbox8.Gtk.Box+BoxChild
			this.btnSalir = new global::Gtk.Button();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString("Salir");
			this.hbox8.Add(this.btnSalir);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.btnSalir]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox8.Add(this.hbox8);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox8]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Control de Catalogo de Cuentas\n");
			this.vbox8.Add(this.label10);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label10]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			this.vbox9.BorderWidth = ((uint)(6));
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox13 = new global::Gtk.HBox();
			this.hbox13.Name = "hbox13";
			this.hbox13.Spacing = 6;
			// Container child hbox13.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por ID:");
			this.hbox13.Add(this.label12);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.label12]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox13.Gtk.Box+BoxChild
			this.txtBuscarID = new global::Gtk.Entry();
			this.txtBuscarID.CanFocus = true;
			this.txtBuscarID.Name = "txtBuscarID";
			this.txtBuscarID.IsEditable = true;
			this.txtBuscarID.InvisibleChar = '•';
			this.hbox13.Add(this.txtBuscarID);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.txtBuscarID]));
			w7.Position = 1;
			// Container child hbox13.Gtk.Box+BoxChild
			this.btnBuscarID = new global::Gtk.Button();
			this.btnBuscarID.CanFocus = true;
			this.btnBuscarID.Name = "btnBuscarID";
			this.btnBuscarID.UseUnderline = true;
			this.btnBuscarID.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox13.Add(this.btnBuscarID);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox13[this.btnBuscarID]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.hbox9.Add(this.hbox13);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox13]));
			w9.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Buscar por Nombre:");
			this.hbox12.Add(this.label11);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.label11]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.txtBuscarNombre = new global::Gtk.Entry();
			this.txtBuscarNombre.CanFocus = true;
			this.txtBuscarNombre.Name = "txtBuscarNombre";
			this.txtBuscarNombre.IsEditable = true;
			this.txtBuscarNombre.InvisibleChar = '•';
			this.hbox12.Add(this.txtBuscarNombre);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.txtBuscarNombre]));
			w11.Position = 1;
			// Container child hbox12.Gtk.Box+BoxChild
			this.btnBuscarNombre = new global::Gtk.Button();
			this.btnBuscarNombre.CanFocus = true;
			this.btnBuscarNombre.Name = "btnBuscarNombre";
			this.btnBuscarNombre.UseUnderline = true;
			this.btnBuscarNombre.Label = global::Mono.Unix.Catalog.GetString("Buscar");
			this.hbox12.Add(this.btnBuscarNombre);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.btnBuscarNombre]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox9.Add(this.hbox12);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.hbox12]));
			w13.Position = 1;
			this.vbox9.Add(this.hbox9);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox9]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			this.hbox10.BorderWidth = ((uint)(6));
			// Container child hbox10.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.tvCatalogoCuentas = new global::Gtk.TreeView();
			this.tvCatalogoCuentas.CanFocus = true;
			this.tvCatalogoCuentas.Name = "tvCatalogoCuentas";
			this.scrolledwindow2.Add(this.tvCatalogoCuentas);
			this.hbox10.Add(this.scrolledwindow2);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.scrolledwindow2]));
			w16.Position = 0;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox14 = new global::Gtk.VBox();
			this.vbox14.Name = "vbox14";
			this.vbox14.Spacing = 6;
			// Container child vbox14.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.Xalign = 1F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("ID del Catalogo de Cuentas:");
			this.vbox14.Add(this.label13);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label13]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			w17.Padding = ((uint)(11));
			// Container child vbox14.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.Xalign = 1F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("Numero de Cuenta:");
			this.vbox14.Add(this.label14);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.label14]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			w18.Padding = ((uint)(2));
			// Container child vbox14.Gtk.Box+BoxChild
			this.vbox15 = new global::Gtk.VBox();
			this.vbox15.Name = "vbox15";
			this.vbox15.Spacing = 6;
			// Container child vbox15.Gtk.Box+BoxChild
			this.vbox16 = new global::Gtk.VBox();
			this.vbox16.Name = "vbox16";
			this.vbox16.Spacing = 6;
			// Container child vbox16.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.Xalign = 1F;
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("Nombre de Cuenta:");
			this.vbox16.Add(this.label17);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label17]));
			w19.Position = 0;
			w19.Expand = false;
			w19.Fill = false;
			w19.Padding = ((uint)(18));
			// Container child vbox16.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label();
			this.label18.Name = "label18";
			this.label18.Xalign = 1F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString("Descripcion de Cuenta:");
			this.vbox16.Add(this.label18);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox16[this.label18]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox15.Add(this.vbox16);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.vbox16]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox15.Gtk.Box+BoxChild
			this.vbox17 = new global::Gtk.VBox();
			this.vbox17.Name = "vbox17";
			this.vbox17.Spacing = 6;
			// Container child vbox17.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.Name = "label19";
			this.label19.Xalign = 1F;
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString("Activo:");
			this.vbox17.Add(this.label19);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.label19]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			w22.Padding = ((uint)(14));
			// Container child vbox17.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label();
			this.label20.Name = "label20";
			this.label20.Xalign = 1F;
			this.label20.LabelProp = global::Mono.Unix.Catalog.GetString("Pais de la Cuenta:");
			this.vbox17.Add(this.label20);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.label20]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			w23.Padding = ((uint)(14));
			// Container child vbox17.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.Xalign = 1F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la Cuenta Padre:");
			this.vbox17.Add(this.label5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.label5]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			w24.Padding = ((uint)(4));
			// Container child vbox17.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.Xalign = 1F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("ID de la Naturaleza de la Cuenta:");
			this.vbox17.Add(this.label4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox17[this.label4]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			w25.Padding = ((uint)(8));
			this.vbox15.Add(this.vbox17);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox15[this.vbox17]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox14.Add(this.vbox15);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox14[this.vbox15]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			this.hbox10.Add(this.vbox14);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox14]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			// Container child vbox10.Gtk.Box+BoxChild
			this.txtIDCatalogoCuentas = new global::Gtk.Entry();
			this.txtIDCatalogoCuentas.CanFocus = true;
			this.txtIDCatalogoCuentas.Name = "txtIDCatalogoCuentas";
			this.txtIDCatalogoCuentas.IsEditable = true;
			this.txtIDCatalogoCuentas.InvisibleChar = '•';
			this.vbox10.Add(this.txtIDCatalogoCuentas);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.txtIDCatalogoCuentas]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			w29.Padding = ((uint)(2));
			// Container child vbox10.Gtk.Box+BoxChild
			this.vbox11 = new global::Gtk.VBox();
			this.vbox11.Name = "vbox11";
			this.vbox11.Spacing = 6;
			// Container child vbox11.Gtk.Box+BoxChild
			this.txtNumeroCuenta = new global::Gtk.Entry();
			this.txtNumeroCuenta.CanFocus = true;
			this.txtNumeroCuenta.Name = "txtNumeroCuenta";
			this.txtNumeroCuenta.IsEditable = true;
			this.txtNumeroCuenta.InvisibleChar = '•';
			this.vbox11.Add(this.txtNumeroCuenta);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.txtNumeroCuenta]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			w30.Padding = ((uint)(3));
			// Container child vbox11.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			// Container child vbox12.Gtk.Box+BoxChild
			this.txtNombreCuenta = new global::Gtk.Entry();
			this.txtNombreCuenta.CanFocus = true;
			this.txtNombreCuenta.Name = "txtNombreCuenta";
			this.txtNombreCuenta.IsEditable = true;
			this.txtNombreCuenta.InvisibleChar = '•';
			this.vbox12.Add(this.txtNombreCuenta);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.txtNombreCuenta]));
			w31.Position = 0;
			w31.Expand = false;
			w31.Fill = false;
			w31.Padding = ((uint)(5));
			// Container child vbox12.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			// Container child vbox13.Gtk.Box+BoxChild
			this.txtDescripcionCuenta = new global::Gtk.Entry();
			this.txtDescripcionCuenta.CanFocus = true;
			this.txtDescripcionCuenta.Name = "txtDescripcionCuenta";
			this.txtDescripcionCuenta.IsEditable = true;
			this.txtDescripcionCuenta.InvisibleChar = '•';
			this.vbox13.Add(this.txtDescripcionCuenta);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.txtDescripcionCuenta]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			w32.Padding = ((uint)(4));
			// Container child vbox13.Gtk.Box+BoxChild
			this.cmbActivo = global::Gtk.ComboBox.NewText();
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("Si"));
			this.cmbActivo.AppendText(global::Mono.Unix.Catalog.GetString("No"));
			this.cmbActivo.Name = "cmbActivo";
			this.cmbActivo.Active = 0;
			this.vbox13.Add(this.cmbActivo);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.cmbActivo]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			w33.Padding = ((uint)(3));
			// Container child vbox13.Gtk.Box+BoxChild
			this.txtPaisCuenta = new global::Gtk.Entry();
			this.txtPaisCuenta.CanFocus = true;
			this.txtPaisCuenta.Name = "txtPaisCuenta";
			this.txtPaisCuenta.IsEditable = true;
			this.txtPaisCuenta.InvisibleChar = '•';
			this.vbox13.Add(this.txtPaisCuenta);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.txtPaisCuenta]));
			w34.Position = 2;
			w34.Expand = false;
			w34.Fill = false;
			w34.Padding = ((uint)(10));
			// Container child vbox13.Gtk.Box+BoxChild
			this.cmbIDCuentaPadre = new global::Gtk.Entry();
			this.cmbIDCuentaPadre.CanFocus = true;
			this.cmbIDCuentaPadre.Name = "cmbIDCuentaPadre";
			this.cmbIDCuentaPadre.IsEditable = true;
			this.cmbIDCuentaPadre.InvisibleChar = '•';
			this.vbox13.Add(this.cmbIDCuentaPadre);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.cmbIDCuentaPadre]));
			w35.Position = 3;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.cmbIDNaturalezaCuenta = global::Gtk.ComboBox.NewText();
			this.cmbIDNaturalezaCuenta.Name = "cmbIDNaturalezaCuenta";
			this.vbox13.Add(this.cmbIDNaturalezaCuenta);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox13[this.cmbIDNaturalezaCuenta]));
			w36.Position = 4;
			w36.Expand = false;
			w36.Fill = false;
			w36.Padding = ((uint)(2));
			this.vbox12.Add(this.vbox13);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox12[this.vbox13]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.vbox11.Add(this.vbox12);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox11[this.vbox12]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			this.vbox10.Add(this.vbox11);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox10[this.vbox11]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			this.hbox10.Add(this.vbox10);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.vbox10]));
			w40.Position = 2;
			w40.Expand = false;
			w40.Fill = false;
			this.vbox9.Add(this.hbox10);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox10]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.hbox11.Add(this.alignment8);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.alignment8]));
			w42.Position = 0;
			// Container child hbox11.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment(0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.hbox11.Add(this.alignment7);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.alignment7]));
			w43.Position = 1;
			// Container child hbox11.Gtk.Box+BoxChild
			this.hbox14 = new global::Gtk.HBox();
			this.hbox14.Name = "hbox14";
			this.hbox14.Spacing = 6;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnNueva = new global::Gtk.Button();
			this.btnNueva.CanFocus = true;
			this.btnNueva.Name = "btnNueva";
			this.btnNueva.UseUnderline = true;
			this.btnNueva.BorderWidth = ((uint)(3));
			this.btnNueva.Label = global::Mono.Unix.Catalog.GetString("Nueva");
			this.hbox14.Add(this.btnNueva);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnNueva]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnAgregar = new global::Gtk.Button();
			this.btnAgregar.CanFocus = true;
			this.btnAgregar.Name = "btnAgregar";
			this.btnAgregar.UseUnderline = true;
			this.btnAgregar.BorderWidth = ((uint)(3));
			this.btnAgregar.Label = global::Mono.Unix.Catalog.GetString("Agregar");
			this.hbox14.Add(this.btnAgregar);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnAgregar]));
			w45.Position = 1;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox14.Gtk.Box+BoxChild
			this.btnEditar = new global::Gtk.Button();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			this.btnEditar.BorderWidth = ((uint)(3));
			this.btnEditar.Label = global::Mono.Unix.Catalog.GetString("Editar");
			this.hbox14.Add(this.btnEditar);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.hbox14[this.btnEditar]));
			w46.Position = 2;
			w46.Expand = false;
			w46.Fill = false;
			this.hbox11.Add(this.hbox14);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.hbox14]));
			w47.Position = 2;
			w47.Expand = false;
			w47.Fill = false;
			this.vbox9.Add(this.hbox11);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox11]));
			w48.Position = 2;
			w48.Expand = false;
			w48.Fill = false;
			this.vbox8.Add(this.vbox9);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.vbox9]));
			w49.Position = 2;
			w49.Expand = false;
			w49.Fill = false;
			this.Add(this.vbox8);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 857;
			this.DefaultHeight = 513;
			this.Show();
			this.btnSalir.Clicked += new global::System.EventHandler(this.OnBtnSalirClicked);
		}
	}
}
